* Quotes
  
  #+BEGIN_QUOTE
  Всё хорошее, что со мной происходит, может начать происходить и с
  вами. От всего плохого, что случилось со мной, я постараюсь вас
  уберечь.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
   For just a moment, pause where you are, and soak in the current
  state of the room around you, and your own state. Just notice what
  this is like.  Now see how this moment is enough. Just as it
  is. Without any need for improvement. It is a wonder, and there’s no
  need for more.  Now see how you are enough. Just as you are. Without
  any need for improvement. You are also a wonder, exactly enough.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  It's the price of doing bussines.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Сначала думать, потом отправлять. Сначала думать, сначала. Не
  наоборот. Подумал, перечитал, сохранил в черновики, подумал ещё,
  прочёл. Стёр.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Не поступай с другими так, как хочешь, чтобы поступали с тобой
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Для того, чтобы научиться хорошо писать, нужно сначала освоить
  критически важный и недооцененный навык *перечитывать написанное*.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Всегда пересчитывай возникающие сомнения. Потом наблюдай, ещё чуть
  позже — игнорируй. «Два раза подумал и хватит»
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Жизнь на минимуме стимуляторов хороша тем, что всегда знаешь, что
  есть ещё что-то, что может спасти тебя завтра.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  you are what you repeatedly do. you are what you repeatedly do. you
  are what you repeatedly do. you are what you repeatedly do.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  “Everybody’s ideas seem obvious to them.” – Derek Sivers
  #+END_QUOTE
  #+BEGIN_QUOTE
  Instead of saying “I don’t have time” try saying “it’s not a
  priority,” and see how that feels.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  -- на какой период из истории россии похоже твое душевное состояние? чем?
			
  -- Первая мировая -- из хорошей семьи, собирался стать, допустим,
  врачом, или инженером, был первым на курсе, все получалось. Потом
  все планы пошли коту под хвост, сидишь в окопе с товарищами, самыми
  разными по происхождению, костерчик горит, ужин готовится, тепло,
  травишь, допустим, байки, ржешь, ибо хрен ли унывать и жаловаться,
  это некомильфо и вообще -- некрасиво, ты же мужик. Да и вообще все,
  м. б., неплохо прямо щас, есть чем себя развлечь, боевые товарищи
  клевые, только все, что ты хотел глобально, --.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  У ноотропов есть неочевидный недостаток: если не ешь и не спишь, то
  все равно СДОХНЕШЬ СУКА СДОХНЕШЬ СДОХНЕШЬ, что печально, конечно.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Нам нравится волшебство, хотя со стороны это всегда выглядит как
  невероятное пижонство.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Как принято и у прочих мелких божеств, неверие в нас мы воспринимаем
  как физическое предательство, как нож в спину. Без веры мы
  исчезаем. Буквально.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Спасибо, дорогое мироздание.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Мы научились прощать. (Но не забывать, никогда не забывать.)
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Не имеет значения, что люди говорят. (Важны связки «контекст-слова»:
  как, в ответ на что, и как поступают потом.)
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Мы часто ошибаемся.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Люди не меняются, но некоторые учатся. Так они становятся лучше и
  более совместимы.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Френдфидовские группы на одного автора хорошо работают, когда
  понимаешь, что одним из главных их плюсов является период остывания,
  “cooldown” для идей, эмоций и реплик. Перестал требовать от них
  немедленной отдачи, научился ждать — и тогда только видишь, как оно
  всё складывается в нужные картины из фрагментов и реплик.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Ну и что, что мы те, кем пугали нас в детстве?
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  «Studies show that the people with the most accurate
  self-perceptions tend to be moderately depressed, suffer from low
  self-esteem, or both.» (L. Mlodinow, "Subliminal: How Your
  Unconcious Mind Rules Your Behavior")
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Ещё этот год научил меня простой штуке: _не существует никакого
  «какой я на самом деле»_. Любое дефолтное состояние — лишь набор
  установок, накопившийся за время развития и воспитания, плюс
  ограничения генотипа/фенотипа (метаболизм, энергообмен, всё
  это). Никакого потенциала, кроме собственных желаний, у меня нет.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  Поэтому всякие призывы «открыть своё призвание» и «найти своё
  истинное я» — они такие, обманчиво-лгущие, потому что вектор не в ту
  сторону. Не «открыть», а скорее «придумать», не «найти», а создать и
  выбрать, не внутри, а вот этими вот руками. И слова про муз
  оказываются в этом контексте бесполезными. Музы создаются (или
  находятся), когда ты начинаешь заниматься тем, что тебе нравится и
  интересно, а не наоборот. А многие вещи становятся интересными,
  когда ты занимаешься ими долго.
  #+END_QUOTE
  
  #+BEGIN_QUOTE
  А поиск интересного строится на симпатичном фундаменте под названием
  «чего бы я хотел устроить, какого эффекта достичь, и как пойму, что
  достиг, _не считая эндорфинчиков_, потому что я уже прекрасно знаю,
  что эндорфинчики тоже лгут». На что будет приятно оглянуться, когда
  оно закончится? Что даст понять, что жизнь того не зря?
  #+END_QUOTE

  (json-encode (org-element-parse-buffer))
