* Пролог. О птичьем оперении

  #+BEGIN_QUOTE
  До открытия Австралии жители Старого Света были убеждены, что все
  лебеди — белые. Их непоколебимая уверенность вполне подтверждалась
  опытом. Встреча с первым черным лебедем, должно быть, сильно удивила
  орнитологов (и вообще всех, кто почему-либо трепетно относится к
  цвету птичьих перьев), но эта история важна но другой причине. Она
  показывает, в каких жестких границах наблюдений или опыта происходит
  наше обучение и как относительны наши познания.
  #+END_QUOTE

  #+BEGIN_QUOTE
  То, что мы будем называть Черным лебедем (с большой буквы), — это
  событие, обладающее следующими тремя характеристиками. Во-первых,
  оно аномально, потому что ничто в прошлом его не
  предвещало. Во-вторых, оно обладает огромной силой
  воздействия. В-третьих, человеческая природа заставляет нас
  придумывать объяснения случившемуся после того, как оно случилось,
  делая событие, сначала воспринятое как сюрприз, объяснимым и
  предсказуемым.
  #+END_QUOTE

  #+BEGIN_QUOTE 
  Успешность человеческих начинаний, как правило, обратно
  пропорциональна предсказуемости их результата.
  #+END_QUOTE

  #+BEGIN_QUOTE
  Опыт показывает, что мы думаем не так много, как нам кажется.
  #+END_QUOTE

* Часть I

** Глава 1. Годы учения эмпирика-скептика

   #+BEGIN_QUOTE
   История непроницаема. Имея налицо результат, вы не видите того, что
   дает толчок ходу событий, — их генератора. Вашему восприятию
   истории органически присуща неполнота, потому что вам не дано
   заглянуть внутрь ящика, разобраться в работе механизма. То, что я
   называю генератором исторических событий, не просматривается в
   самих событиях — так же как в деяниях богов не угадываются их
   намерения. Как говорится, неисповедимы пути Господни.

   Подобный разрыв существует между блюдами, которые приносят вам в
   ресторане, и тем, что творится на кухне.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Категоризация необходима людям, но она оборачивается бедой, когда в
   категории начинают видеть нечто окончательное, исключающее зыбкость
   границ — не говоря уже о пересмотре самих категорий.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Поэтому я остался (и по сей день остаюсь) квант-инженером и
   трейдером, однако устроил свою жизнь так: работал по минимуму, но
   интенсивно (и с увлечением), сосредоточивался только на
   высокотехнических аспектах, никогда не посещал деловых встреч,
   избегал компании "успешных людей", не читающих книжек, и примерно
   каждый четвертый год целиком посвящал ликвидации пробелов в своем
   научном и философском образовании. Чтобы постепенно вынашивать мою
   главную идею, мне надо было стать фланером, профессиональным
   медитатором, сидеть в кафе, гулять без поводка, привязанного к
   рабочему столу и организации, спать столько, сколько душе угодно,
   читать запоем и никому ничего не объяснять.
   #+END_QUOTE

** Глава 2. Черный Лебедь Евгении

   #+BEGIN_QUOTE
   Кроме того, я уверен, что переворот в социальной жизни произвел не
   граммофон, а чья-то великая, но дискриминационная идея изобрести
   алфавит, который позволяет нам сохранять и воспроизводить
   информацию. Колесо закрутилось быстрее, когда другому изобретателю
   пришла в голову еще более опасная и зловредная мысль запустить
   печатный станок, позволив слову преодолеть границы и дав толчок
   тому, что в конце концов привело к такому положению вещей, при
   котором победитель получает все. Какой же несправедливостью чревато
   распространение книг? При помощи алфавита можно точно и многократно
   воспроизводить истории и идеи без дополнительных усилий со стороны
   автора. Автор даже не обязан быть живым; нередко смерть — хороший
   карьерный шаг для писателя.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Нам трудно признать, что мы превозносим произведение искусства не
   только потому, что оно прекрасно, но и для того, чтобы ощущать свою
   принадлежность к сообществу. Подражание позволяет нам стать ближе к
   другим людям, то есть другим подражателям. Это борьба с
   одиночеством.
   #+END_QUOTE

** Глава 3. Спекулянт и проститутка
** Глава 4. Тысяча и один день, или Как не быть лохом
** Глава 5. Докозательство-шмоказательство!

   #+BEGIN_QUOTE
   Современный мир, являясь Крайнестаном, целиком зависит от редких —
   крайне редких — событий. В нем Черный лебедь может появиться после
   тысяч и тысяч Белых, поэтому нам следует воздерживаться от суждений
   гораздо дольше, чем нам свойственно.
   #+END_QUOTE

** Глава 6. Искажение нарратива

   #+BEGIN_QUOTE
   Если притормозить работу левого полушария правши (воздействуя
   низкочастотными магнитными импульсами на левые лобно-височные доли
   мозга), вероятность того, что он пропустит ошибку при чтении
   приведенного выше текста, снизится. Наша склонность повсюду искать
   смысл и идею мешает нам видеть смыслообразующие детали. Однако люди,
   у которых работа левого полушария приторможена, реалистичнее смотрят
   на мир — они лучше и живее рисуют. В их мозгу отчетливее
   запечатлеваются сами объекты, очищенные от шелухи теорий, историй и
   предрассудков.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Как избавиться от этой непрестанной головной боли?  Не пытайтесь
   заставлять себя не думать: только еще сильнее разбередите
   рану. Более действенный способ — принять случившееся как
   неизбежность. Мол, чему суждено было произойти, то и произошло, и
   нечего без толку себя пилить. Но как этого добиться? Конечно же с
   помощью нарратива. Люди, которые каждый вечер тратят хотя бы
   пятнадцать минут на то, чтобы написать о происшедших за день
   неприятностях, значительно лучше справляются со стрессом. Их не
   подтачивает чувство вины; они как бы снимают с себя ответственность,
   воспринимая все как предначертанное.

   Если уровень неопределенности в вашем деле высок, если вы постоянно
   казните себя за поступки, которые привели к нежелательным
   последствиям, для начала заведите дневник.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Система 1. Эмпирическии тип мышления — безусильныи, автоматический,
   быстрый, бессознательный, параллельнопоточный и порой плодящий
   ошибки. Это то, что мы называем интуицией или озарением (по названию
   бестселлера Малкольма Гладуэлла*, прославившего эти мгновенные акты
   отваги). Озарение молниеносно и потому в высшей степени
   эмоционально. Оно снабжает нас "комбинациями быстрого набора", а
   по-ученому — эвристиками, которые позволяют нам действовать
   незамедлительно и эффективно. Дэн Голдстейн считает этот
   эвристический метод "высокоскоростным и экономным". Есть и
   противники такой спешки. "Комбинации быстрого набора" конечно же
   очень полезны, но они могут приводить к грубейшим ошибкам. Из этой
   идеи выросла целая исследовательская школа "эвристик и
   предубеждений".

   Система 2. Рационалистический тип мышления — это то, что в быту
   называется думаньем. Обычно мы включаем "думал ку" только в
   аудитории, так как думанье — процесс трудоемкий (даже у французов),
   основательный, медленный, логический, последовательный, постепенный
   и осознанный.  Рационалистический тип мышления порождает меньше
   ошибок, чем эмпирический, к тому же, зная, каким образом был получен
   тот или иной результат, можно по шагам проследить ход своих
   рассуждений и скорректировать их в зависимости от ситуации.
  
   Опасность ошибки подстерегает нас тогда, когда мы полагаем, что
   пользуемся Системой 2, а на самом деле эксплуатируем Систему 1. Как
   это может быть? Поскольку наши реакции спонтанны и неосознанны,
   Система 1 функционирует без нашего ведома!
   #+END_QUOTE

** Глава 7. Жизнь на пороге надежды

** Глава 8. Любимец удачи Джакомо Казанова: проблема скрытых свидетельств

   #+BEGIN_QUOTE
   На самом деле изобилие авнтюристов, ощущающих себя баловнями
   Фортуны, объясняется тем, что авантюристов вообще вокруг пруд пруди,
   и мы ничего не знаем о тех из них, кому не повезло.
   #+END_QUOTE

** Глава 9. Игровая ошибка, или Неопределенность "ботаника"

   #+BEGIN_QUOTE 
   Все проблемы, обсуждавшиеся в первой части, по сути
   сводятся к одной. Бывает, что размышляешь о чем-то так долго, что
   становишься одержимым. И вроде бы мыслей много, но между ними нет
   видимой связи; объединяющая их логика пока что скрыта от вас. Но в
   глубине души вы понимаете, что эта логика есть. А всякие там (как
   окрестил их Ницше) bildungsphilisters, или ученые филистеры,
   синие воротнички философской науки, твердят, что вы копаете в
   слишком разных пластах. Вы возражаете, что разделение между научными
   дисциплинами искусственно и произвольно, но это не помогает. Наконец
   вы заявляете, что вообще-то вы шофер лимузина, и вас оставляют в
   покое. Так лучше, потому что не нужно отождествлять себя с миром
   науки, не нужно подвергаться ампутации, чтобы втиснуться в
   прокрустово ложе специализации. И вдруг — один легкий толчок, и вы
   видите проблему как единое целое.
   #+END_QUOTE

* Часть II

** Глава 10. Предсказательный парадокс

** Глава 11. Открытие на основе птичьего помета

   #+BEGIN_QUOTE
   В тридцать с лишним лет Пуанкаре стал плодовитым литератором. Он
   торопился (он и умереть слишком уж поторопился — в 58 лет), так
   спешил, что не утруждался исправлением опечаток и грамматических
   ошибок в своих эссе, даже если замечал их. Считал нецелесообразным
   тратить драгоценное время на такие мелочи. Подобных гениев больше
   не рождается — или им больше не дозволяют писать так, как они считают
   нужным.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Корпорации пусть себе лопаются, раз им так угодно, тем самым
   поддерживая нас, потребителей, пересыпая свое богатство в наши
   карманы, — чем больше банкротств, тем нам лучше. А вот
   правительство — контора посерьезнее, и нам нужно быть начеку, а то
   того и гляди придется расплачиваться за его глупость.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Итак, платоникам присущи взгляд "сверху вниз", стереотипность и
   узость мышления, защищенность на собственных интересах,
   обезличенность. Не платоникам свойственны взгляд "снизу вверх",
   открытость мышления, скептицизм и эмпирический склад ума.

   Почему я выбрал именно великого Платона для подобных разбирательств?
   Думаю, достаточно привести один пример, иллюстрирующий характерную
   особенность его мышления: Платон считал, что человек должен одинаково
   хорошо владеть и правой и левой рукой. Противное казалось ему
   "бессмыслицей". Он считал предпочтение одной конечности другой
   уродством, вызванным "недомыслием кормилиц и матерей". Асимметрия его
   раздражала: свои представления о прекрасном он переносил на
   реальность. До Луи Пастера никто не понимал, что молекулы могут быть
   "левшами" и "правшами" и что между ними — огромная разница.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Как говорил Уоррен Баффет, не спрашивайте парикмахера, не пора ли
   вам стричься, — не спрашивайте ученого, важно ли то, чем он
   занимается.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Я уже говорил, что порой цеховые интересы академиков сильно
   расходятся с интересами самой науки. Никак не пойму, почему
   либертарианцы не раскритиковали до сих пор "теньюр", то есть
   пожизненные профессорские должности. Не потому ли, что многие
   либертарианцы сами их занимают?
   #+END_QUOTE

   #+BEGIN_QUOTE
   Зная все возможные характеристики физической системы, теоретически
   (хотя, как мы выяснили, не практически) можно предсказать ее
   поведение в будущем. Но это касается только неодушевленных
   объектов. Как только в нашу систему привносится "человеческий
   фактор", все пророчества идут насмарку. Это совершенно другая
   задача: предсказывать будущее для системы, элементами которой
   являются люди, конечно, если вы исходите из того, что они живые и
   обладают свободой выбора.

   Если я при данных условиях смогу предсказать все ваши действия, то
   вы, возможно, не так свободны, как вам кажется. Вы — автомат,
   реагирующий на внешние раздражители. Вы — раб судьбы. А иллюзия
   свободы воли может быть сведена к уравнению, которое описывает
   результат взаимодействия молекул. Это все равно что изучать
   механику часов: гений, обладающий достаточным знанием начальных
   условий и звеньев причинно-следственных цепочек, мог бы вычислить и
   ваши действия в будущем. А не почувствовали бы вы себя в таком мире
   несчастным пленником?

   Однако, веруя в свободу выбора, невозможно искренне верить в
   экономические и социальные прогнозы. Нельзя предсказать, как люди
   будут действовать.
   #+END_QUOTE

** Глава 12. Эпистемократия, мечта

   #+BEGIN_QUOTE
   Тот, кто не отличается эпистемической самонадеянностью, как правило,
   не очень-то всем заметен, будто стеснительный гость на вечеринке. У
   нас не принято уважать скромных людей, которые не торопятся с
   суждениями. Они обладают эпистемической скромностью. Представьте себе
   беднягу, которого вечно терзает сознание собственного невежества. У
   него нет куража, свойственного кретинам, зато есть редкое мужество
   честно сказать "Я не знаю". Он не боится выглядеть дураком или, хуже
   того, невеждой. Он сомневается, он не решается действовать, он
   мучительно анализирует последствия возможных ошибок. Он размышляет,
   размышляет и размышляет—до полного изнеможения и нервного истощения.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Само слово эссе означает нечто пробное, умозрительное и
   неопределенное.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Монтеню было важно узнавать что-то о себе и давать нам возможность
   узнавать что-то о нем, но при этом он обсуждал проблемы и темы,
   затрагивающие каждого из нас, — общечеловеческие. На стене его
   башни красовалось и высказывание латинского поэта Теренция: "Homo
   sum: humani nil a me alienum puto". Я человек, и ничто человеческое
   мне не чуждо.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Монтень отличался и от сорбоннских академиков, и от
   профессиональных литераторов в двух отношениях. Во-первых, он был
   человеком дела: поработал судьей, коммерсантом и мэром Бордо — до
   того, как ушел на покой, чтобы поразмышлять о собственной жизни и
   главным образом о собственном знании. Во-вторых, он был
   антидогматиком. *Очаровательный скептик, ошибающийся, неуверенный,
   субъективный, сомневающийся писатель, он прежде всего хотел
   следовать великой классической традиции и оставаться человеком.*
   #+END_QUOTE

   #+BEGIN_QUOTE
   "Чернолебяжья" асимметрия позволяет быть уверенным в том, что
   неправильно, но не в том, что, с твоей точки зрения, правильно.
   #+END_QUOTE

   #+BEGIN_QUOTE 
   "Слепое пятно" восприятия: мы не сопоставляем наши
   сегодняшние мысли о завтрашнем дне с нашими вчерашними мыслями о
   дне сегодняшнем. Из-за этого дефекта интроспекции мы не замечаем
   очевидных расхождений между нашими прошлыми прогнозами и тем, как
   все обернулось в реальности.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Сходите в Бронкский зоопарк, в отдел приматов, и вы увидите
   счастливую семью наших ближайших родственников, живущих своей
   суматошной общественной жизнью. Вы также увидите множество
   хохочущих туристов, забавляющихся этой пародией на себя. Теперь
   представьте, что вы принадлежите к более развитому виду (скажем,
   являетесь "истинным" философом, настоящим мудрецом), с гораздо
   более высоким уровнем интеллекта, чем у приматов человеческого
   образца. Вы, конечно, будете смеяться над этими людьми, которые
   смеются над приматами, не доросшими до человека. Разумеется, тем,
   кто потешается над обезьянами, не приходит в голову, что на них
   тоже кто-то может смотреть свысока, — если бы это вдруг до них
   дошло, они бы очень расстроились. И перестали бы смеяться.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Аналогичным образом особенности освоения прошлого человеческим
   мозгом заставляют нас верить в окончательность наших решений — и
   не учитывать того, что наши предшественники тоже считали, что
   знают окончательные решения. Мы смеемся над другими, не понимая,
   что довольно скоро у кого-нибудь будет ровно столько же оснований
   смеяться над нами. Осознание этого требует рекурсивного мышления,
   которое я упоминал в Прологе, а в нем мы не сильны.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Гелен, в отличие от других пророков, мог в деталях провидеть прошлое —
   без всяких подсказок. Он провидел вспять.

   Наша проблема не только в том, что мы не ведаем будущего, о прошлом мы
   тоже не особо много ведаем. Чтобы знать историю, нам совершенно
   необходим такой человек, как Гелен.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Редактор электронных таблиц способен сгенерировать случайную
   последовательность чисел, которую можно назвать историей. Каким
   образом? В компьютерную программу закладывается затейливое нелинейное
   уравнение, которое выдает числа, кажущиеся случайными. Уравнение
   несложное: зная его, можно предсказывать последовательность
   бесконечно. Но самостоятельно вывести уравнение из имеющихся данных, а
   значит, и просчитать цепочку вперед, — человеку не под силу. А ведь я
   говорю о простейшей однострочной компьютерной программе, которая
   перетасовывает горсть чисел, а не о миллиардах одновременных событий,
   составляющих настоящую историю мира. Другими словами, даже если бы
   история была последовательностью не случайной, а сгенерированной неким
   "всемирным уравнением", нам все равно не следовало бы считать ее
   таковой и называть "детерминированным хаосом", поскольку вывести это
   уравнение нам не дано.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Случайность -- это неполная информация.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Так вот, суть асимметричности итогов (а это основная идея книги)
   такова: я никогда не буду знать неизвестное, поскольку оно по
   определению неизвестно. Но при этом я могу гадать, как оно на мне
   отразится, плохо или хорошо, и принимать решения исходя из
   собственных догадок и умозаключений.

   Рассуждение в таком роде часто ошибочно называют "пари Паскаля", в
   честь философа и (думающего) математика Блеза Паскаля. Он
   высказался примерно так: я не знаю, существует ли Бог, но знаю, что
   своим атеизмом мало чего добьюсь, если его нет, но очень себе
   наврежу, если он есть. Это склоняет меня к вере в Бога.

   Аргументация Паскаля, с точки зрения теолога, крайне некорректна:
   только наивный человек может считать, что Бог не захочет нас
   наказать за корысть в вере. Или придется предположить (но это уже,
   пожалуй, перебор), что Бог тоже наивен. (Бертран Рассел, по слухам,
   говорил, что Богу пришлось бы сотворить дураков, чтобы аргументация
   Паскаля оказалась верной.)

   Но идея, стоящая за Паскалевым пари, может быть широко применима и
   за пределами теологии. Она переворачивает всю парадигму знания с
   ног на голову. Она устраняет необходимость (тщетно) ломать голову
   над закономерностями редкостных событий и позволяет нам целиком
   сосредоточиться на выгоде, которую можно получить, если событие
   все-таки происходит. Вероятность очень редких событий невычисляема;
   воздействие события на нас предсказать гораздо проще (чем
   маловероятнее событие, тем, конечно, туманнее картина). Мы вполне в
   состоянии представить последствия события, даже если не знаем,
   насколько велика его вероятность. Я не знаю, какова вероятность
   землетрясения, но я могу вообразить, что бы оно сотворило с
   Сан-Франциско. Итак, по Паскалю, для принятия решений вы должны
   сосредоточиться на последствиях (которые вы можете знать), а не на
   вероятности события (степень которой вы знать не можете) — это
   главное правило идеи неопределенности.
   #+END_QUOTE

* Часть III

** Глава 15. Кривая нормального распределения, великий интеллектуальный обман

