Биология поведения: гуморальные механизмы 

* Взаимосвязь функций организма

** Биологические основы поведения человека

   Человека отличает от животных понятийная речь, чувство юмора,
   нравственность и потребность самопознания. Механизмы поведения
   человека те же, что и у животных.

*** Принцип Оккама

    Сущности не должны быть умножаемы сверх необходимости.

    Самое простое объяснение не обязательно самое правильное. Но
    простую гипотезу следует отвергнуть только, если более сложная
    оставляет необъясненными меньшее количество фактов.

    То или иное действие нельзя интерпретировать как результат
    проявления какой-либо высшей психической функции, если его можно
    объяснить на основе наличия у животного способности, занимающей
    более низкую ступень на психологической шкале.

    Для объяснения поведения человека следует использовать те же
    понятия, что и при описании поведения животных. Только когда этого
    окажется недостаточно -- можно вводить новые понятия.

** Единство психического и соматического

*** Три функции личности

    Выделяют три функции личности: когнитивная (сознательная),
    аффективная (эмоциональная) и моторная (двигательная).

    Психические процессы нерасторжимо связаны с соматическими.

    Примеры:

    1) Связь аффективной и когнитивной функций

       Незавершенное действие оставляет более глубокий след в памяти
       (эффект Зейгарник). Частный случай общего правила: лучше
       запоминаются эмоционально окрашенные события.

    2) Связь аффективной и когнитивной функции с моторной

       Психика проявляется в моторике, а изменения моторики влияют на
       психику. Хорошо известный термин "транквилизатор" впервые был
       использован для названия массивного кресла, в котором фиксировали
       больных с психомоторным возбуждением. Ограничение подвижности
       приводит к торможению аффекта (больной перестает беспокоиться) и
       когнитивному торможению (больной не стремиться больше что-то
       предпринять).

       Достаточно жесткие законы, связывающие моторику и
       психику, дают нам возможность судить о психических процессах
       другого человека. Опытный психиатр может поставить
       предварительный диагноз, пока больной идет от двери кабинета к
       столу врача.

*** Связь психики и поведения с гормонами

    Типы влияния гормонов на психику и поведение:

    - Организация
    
      Гормон организует формирование ЦНС. Например, соотношение половых
      гормонов в эмбриональный период определяет организацию ЦНС по
      мужскому, либо по женского типу. Недостаток гормонов щитовидной
      железы в раннем детстве приводит к дефектам строения ЦНС и, как
      следствие, неизлечимому слабоумию.

    - Индукция

      Гормон вызывает данную психологическую реакцию независимо от
      состояния организма. У человека обнаружено лишь две индуцируемые
      гормонами формы поведения: пищевое, которое индуцируется
      введением малых доз инсулина, и питьевое, индуцируемое введением
      альдостерона и других минералкортикоидов. Это примеры индукции
      поведения за счет создания витальных потребностей. Гормонами
      индуцируются два аффективных состояния: тревога индуцируется
      кортиколиберином, а эйфория -- эндорфинами. Все остальные
      гормональные влияния на психику и поведение человека являются
      либо модуляцией, либо обеспечением.

    - Модуляция

      Психические процессы усиливаются или тормозятся пропорционально
      концентрации гормона, но гормональные влияния проявляются только
      при определенном исходном психологическом состоянии. Если
      говорится, что гормон модулирует поведение, это значит: гомон
      усиливает или ослабляет проявление данного поведения, но не
      может вызывать его в любых условиях. Модуляция -- самый
      распространенный тип влияния гуморальных факторов на поведение.

    - Обеспечение

      Для проявления любой формы поведения необходим определенный
      уровень гормона. Этот уровень обеспечивает протекание
      какого-либо процесса, но при дальнейшем росте концентрации
      гормона данная форма поведения не усиливается. Усиление может
      происходить (но не обязательно) при очень больших
      концентрациях. Например, большая доза кортизола может вызвать
      маниакальное состояние (кортизоловый психоз).

      Обеспечение, но не стимуляция как принцип связи между двумя
      функциями имеет место не только в психосоматических
      взаимоотношениях. Например, память является функцией необходимой
      для интеллектуальной активности. При ослаблении памяти --
      вследствие ли дефектов развития, заболевание, возрастных
      изменений или простой усталости -- страдают все формы умственной
      деятельности, начиная с простой способности ориентироваться в
      пространстве. После достижения определенного уровня дальнейшее
      увеличение памяти не ведет к усиление умственных
      способностей. Таким образом, память обеспечивает, но не
      стимулирует интеллектуальную деятельность человека.


    Висцеральные реакции отражают психические процессы, поэтому
    гормоны служат маркерами психических процессов.

    Использование гормональных показателей как отражение психических
    явлений является одним из аспектов объективной психологии.

    #+BEGIN_QUOTE
    Связи психики с висцеральными системами подчас неожиданны для
    непосвященного. Например, тема диссертации великого отечественно
    ученого В. М. Бехтерева "Опыт клинического исследования
    температуры при некоторых душевных заболеваниях" (1881). Многие
    психичесие состояния, в том числе болезненные, характеризуются
    особой температурной кривой, т.е. измерение температуры помогает
    уточнить диагноз. 
    #+END_QUOTE

** Три школы объективной психологии

   Объективная психология основана на количественном измерении
   моторных и висцеральных функций.

*** Русская школа

    В школе И. П. Павлова для объективного изучения психики
    использовались висцеральные реакции.

    В школе В. М. Бехтерева для объективного изучения психики
    использовались моторные реакции.

*** Бихевиоризм

    Бихевиористы изучают не психику, а поведение, т.е. закономерность
    между стимулом и двигательной реакцией человека или животного.

    Бихевиористы считают, что любого можно обучить чему угодно.

    Основным методом бихевиоризма является инструментальный условный
    рефлекс.

    #+BEGIN_QUOTE
    Всякая наука характеризуется предметом и методом.
    #+END_QUOTE

    #+BEGIN_QUOTE
    В Африке живут гигантские хомяковые крысы (Cricetomys gambianus)
    Это крупные твари весом до 2 кг и длинной тела до 70 см. Они
    терпимо относятся к человеку, и с ними достаточно легко
    работать. Сейчас в Бельгии их обучают искать и уничтожать
    противопехотные мины.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Конрад Лоренц советовал стрелять из рогатки в собаку, срывающуюся
    с поводка, но не наказывать ее, когда она, набегавшись, вернется к
    хозяину, -- в таком случае условным стимулом, сочетающимся с
    наказанием, окажется возвращение к хозяину. Поэтому же женам
    рекомендуют делать выговор загулявшим детям и мужьям не сразу
    после их возвращения домой, а после того, как они выспятся.
    #+END_QUOTE

*** Этология

    Этология -- наука о комплексном поведении в естественных условиях
    обитания животного.

    Этология изучает врожденные (инстинктивные) формы поведения.

    #+BEGIN_QUOTE
    К сожалению, в общественном сознании все еще распространено
    представление о качественном отличие человека от остальных
    животных. Широко распространено ошибочное представление о
    ничтожной роли врожденных особенностей поведения человека. Поэтому
    регулярно создаются вредные теории воспитания.
    #+END_QUOTE

** Единство нервной и гуморальной регуляции

   Гуморальная регуляция и нервная регуляция -- две стороны единой
   системы нервно-гуморальной регуляции.

* Стуруктура поведения

** Понятие поведения

   Поведение включает три момента: движение; удовлетворение
   потребности; изменение среды или приспособление к ней.

   Поведение человека или животного -- это двигательная активность,
   цель которой -- цдовлетворение потребности, возникшей в результате
   изменения среды -- внутренней или внешней (физической или
   социальной), и которая направлена на возвращение среды к прежнему
   состоянию либо на приспособление к новому состоянию
   среды. Возвращение среды к прежнему состоянию называется поведением
   типа А, а приспособлением к новой среде -- поведением типа Б.

** Потребности

   Различные формы поведения чаще всего классифицируют исходя из
   потребностей, удовлетворению которой служит данный поведенческий
   акт.

   Потребности разделяют на три группы:

   - витальные
   - социальные 
   - идеальные

   Витальные и социальные потребности одинаковы у человека и животных.

*** Витальные потребности

    * Самосохранение -- потребности в поступление пищи и воды, в
      сохранении физической целостности организма.

    * Самовоспроизведение -- потребность иметь потомство и заботиться о нем.

    * Самоподдержание -- потребности в функциональной целостности
      организма и поддержании его работоспособности. В частности:

      + Потребность в сенсорном притоке

        На то, что активное состояние мозга поддерживается суммой
        раздражений от всех органов чувств, впервые указал
        И. М. Сеченов в "Рефлексах головного мозга". В дальнейшем это
        положение получило многочисленные экспериментальные
        подтверждения. Животное, которому в эксперименте разрушают
        структуры мозга, в которых расположены сенсорные входы,
        впадает в состояние, неоличимое от глубокой потери сознания.
        Для удовлетворения сенсорной потребности не имеет значения
        информационная нагрузка, а имеют значение количество и
        разнообразие раздражений органов чувств.

      + Потребность в информационном притоке -- информация не должна
        быть значимой для удовлетворения других потребностей
        человека. Главный фактор -- ее количество.

      + Потребность в эмоциях

      + Гедонистическая потребность

    Потребности в сенсорном и информационном притоке биологически
    обоснованы тем, что сбор информации об окружающей среде --
    жизненно необходимое условие выживания каждого животного.

    В условиях сенсорного голода потребность в сенсорных ощущениях и
    потребность в информации можно удовлетворить сенсорным потоком
    от работающих мышц.


    #+BEGIN_QUOTE
    Ограничение сенсорного и информационного притока ведет к
    эмоциональным расстройствам.  Писатели XIX века, например
    Н. С. Лесков и Анатоль Франс, неоднократно отмечали дурной нрав
    монахов и монахинь. То же самое можно наблюдать и сегодня в
    замкнутых коллективах (дальние экспедиции, гарнизоны, закрытые
    учебные заведения). Это объясняется тем, что в условиях сенсорного
    и информационного голода любое, даже незначительное, событие
    приобретает яркую эмоциональную окраску, неадекватную значению
    этого изменения в окружающей среде. Психологический дискомфорт в
    условиях информационного голода может легко переходить в
    психические расстройства. Поэтому в обязательную комплектацию
    полярных экспедиций входят смирительные рубашки, ибо, так
    называемое "экспедиционное бешенство" -- обычное явление.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Отсутствие потребности вести здоровый образ жизни не сказывается
    на способности человека оставить жизнеспособное потомство, тогда
    как живые организмы, лишенные витальных потребностей, например
    потребности в информации, если и вырастают до репродуктивного
    возраста, чаще не оставляют потомства.
    #+END_QUOTE

*** Социальные потребности

    1) Потребность в самоидентификации -- принадлежности к группе --
       основная социальная потребность.

    2) Потребность в доминировании -- потребность в приоритетном
       доступе к витальным ресурсам.

    3) Потребность в лидерстве -- потребность в свободе движений в
       социальной стуруктуре общества.

    4) Потребность в подчинении.

    #+BEGIN_QUOTE
    Другой распространенный пример комбинированного сообщества --
    человек и его автомобиль. Нежные слова, которые употребляет
    человек, обращаясь к своей машине, свидетельствуют о том, что
    отношение к машине гораздо богаче отношений к предмету роскоши как
    показателю социального положения, знаку престижа. В английском
    языке все объекты, кроме людей, обозначаются местоимениями
    среднего рода. Исключение составляют домашние животные и
    автомобили. Автомобиль для мужчины -- she, для женщины --
    he.
    #+END_QUOTE

*** Идеальные потребности

    Идеальными называются потребности, отсутстувующие у
    животных. Например, потребность в познании.

*** Соотношения потребностей

    Сложные формы поведения человека являются удовлетворением
    определенного набора потребностей.

    #+BEGIN_QUOTE
    В тех случаях, когда от любви до ненависти оказался один шаг,
    можно уверенно сказать, что в "любви" преобладала мотивация,
    сформированная на основе потребности в лидерстве. Поскольку не
    удалось сориентировать поведение объекта на себя, т.е. добиться
    взаимности, субъект, рационализируя неудачу, объясняет себе, что
    бывший предмет его любви плох, и для доказательства этого не
    упускает случая унизить его.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Как правило, человек, любящий другого за то, что он -- его
    создание, не допускает проявлений самостоятельности предмета
    своего чувства.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Люди, любящие собак, имеют, как правило, выраженную потребность в
    лидерстве, которую не могут удовлетворить в отношениях в других
    социальных стуруктурах. Те же, кто предпочитает собакам кошек,
    либо не имеют выраженной потребности в лидерстве, либо реализуют
    ее в других сообществах. Этим объясняется хорошо язвестная
    закономерность большей любви женщин к кошкам, а мужчин -- к
    собакам.
    #+END_QUOTE

** Поведенческий акт

   Схема поведенческого акта:

   1) потребности
   2) мотивация
      * тревожность
      * сбор информации о среде
      * извлечение информации из памяти
      * эмоции
      * выбор или выработка программы действий
   3) поведение
   4) проверка результата
      * потребность удовлетворена -- положительные эмоции --
        дополнение памяти
      * потребность не удовлетворена -- отрицательные эмоции --
        изменение программы

*** Потребности

    Цель поведения -- удовлетворение потребности. Потребности
    возникают:

    * в ответ на изменение во внешней или внутренней среде
    * в результате накопления внутренней энергии

*** Мотивация

    Мотивация -- это механизм активации памяти о способах
    удовлетворения потребности. Общая эффективность его работы зависит
    от уровня тревоги.

    Степень мотивации прямо отражается на уровне тревоги и наоборот.

    В рамках мотивационного возбуждения происходит не сбор всей
    доступной информации, а поиск ключевого стимула, который позволит
    охарактеризовать ситуацию как знакомую, такую, с которой человек
    (или животное) уже сталкивался.

    Сила эмоции пропорциональна неопределенности ситуации.

*** Программа действий

    Выбор или создание программы действий непосредственно
    предшествует двигательному акту. 

    Перебор хранящихся в памяти ФКД (фиксированных комплексов
    действий) и сбор информации об обстановке в которой находится
    человек или животное, идут параллельно до тех пор, пока в
    окружающей среде не будет найдена некая совокупность признаков,
    соответствующая одному из имеющихся ФКД. Данный ФКД и реализуется
    как программа действий. Эта совокупность характеристик внешней
    среды называется ключевым или сигнальным стимулом.

    Подавляющее большинство поведенческих актов человек совершает,
    используя уже готовую программу поведения.

    #+BEGIN_QUOTE
    Различия между людьми заключаются в том, что одни прекращают
    процесс накопления программ достаточно рано, в юные годы, а
    другие накапливают их всю жизнь. Первые применяют программы,
    часто только приблизительно подходящие к данной ситуации, а
    вторые нередко тратят много времени на исследование ситуации и
    подбор наилушей программы.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Уровень мотивации животных можно повысить, например, через
    повышение тревожности.
    #+END_QUOTE

*** Сопостовление полученного результата с ожидаемым

    Эмоции -- мощный регулятор когнитивных функций. Отрицательные
    эмоции возникают в случае несовпадения полученного результата и
    побуждают организм изменить программу действия. Положительные
    эмоции возникают при совпадении полученного результата с
    ожидаемым, т.е. при удовлетворении потребности, и стимулируют
    закрепление в памяти нового сочетания -- изменения в среде и
    эффективный ФКД.

*** Индивидуальные особенности

    Индивидуальные психологические особенности отражаются не только в
    количественных различий между людьми, но и в качественных
    различиях в структуре их поведения. 

** Действие гуморальных факторов на разных этапах поведенческого акта

*** Потребности

    Примеры: голод (снижение глюкозы в крови), жажда (нарушенный
    водно-солевой баланс), потребность в половом контакте
    (гонадолиберин).

*** Мотивация

    Гуморальные факторы принимают воздействуют на все этапы
    мотивации:

    * Тревожность -- оскитоцин, вазопрессин, кортиколиберин

    * Сбор информации о среде -- гормоны модулируют функционирование
      сенсорных систем.

    * Извлечение информации из памяти -- вазопрессин, уровень глюкозы
      в крови.

    * Эмоции -- продукт главным образом нервных процессов, однако
      стабильные эмоциональные состояния (аффективный фон) находятся
      под гормональным контролем -- эндорфины, окситоцин, вазопрессин,
      эндорфины, дофамин

    * Выбор или выработка программы действий -- адреналин способствует
      поведению типа А, вазопрессин способствует поведению типа Б,
      окситоцин способствует материнскому поведению, половые гормоны
      модулируют половое поведение

*** Движение

    Гуморальные факторы участвуют в обеспечении и стимуляции движения
    на нескольких уровнях:

    * на уровне мышц -- андрогены модулируют анаболический аспект
      метаболизма и обеспечивают двигательную активность

    * на уровне общего обмена веществ -- гормоны щитовидной железы
      обеспечивают двигательную активность

    * на уровне нервных центров, управляющих движением -- кортизол
      усиливает транспорт глюкозы в нервные клетки, норадреналин
      восстанавливает работоспособность утомленной мышцы (феномен
      Орбели--Гинецинского)

    Двигательную активность так же модулируют тестостерон, эстрадиол и
    мелатонин.

*** Психические состояния

    * Состояния, связанные с ритмическими процессами в организме

      + мелатонин регулирует ритмику процессов, связанных с
        чередованиями дня и ночи, а так же  модулирует настроение

      + общяя активность зависит от уровня функционирования клеток
        ЦНС, который обеспечивается гормонами щитовидной железы, коры
        надпочечников (кортизол) и гонадами (андрогены)

    * Состояния, связанные с неудовлетворенными потребностями -- роль
      гуморальных факторов в состояниях этой группы зависит от
      конкретной потребности, породившей сотояние

    * Состояния, к которым относятся разнообразные проявления стресса

      + стресс -- АКТГ, адреналин

      + тревога -- кортиколиберин

    * Состояния

    Используемое в психологии понятие "психические состояния" включает
    разнородные с биологической точки зрения категории.

    Гуморальные факторы учавствуют в формировании и поддержании
    различных психических состояний. При этом они действуют, как
    правило, с нервными факторами.

    Положительные эмоции связаны с усилением секреции эндорфинов, а не
    адреналина.

    Окситоцин -- это гормон, стимулирующий состояние безмятежности,
    т.е. естественный противотревожный гуморальный фактор.

    Половой гормон -- гонадолиберин -- стимулирует состояние
    эйфории. Он является естественным антидепрессантом.

    #+BEGIN_QUOTE
    При низкой тревожности, конституциональной или вызванной введением
    фармокологического препаратов, наличие потребностей с трудом
    приводит к образованию мотивации.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Гуморального фактор, вызывающего субдепрессивные состояния не
    существует. В настоящее время твердо установлено, что повышенный
    уровень синтеза и секреции стрессорных гормонов (т.е. гормонов
    синтез и секреция которых повышается при стрессе) не является
    причиной депрессии и субдепрессивных состояний.
    #+END_QUOTE

* Гуморальная система

** Общая часть

   Гуморальная и нервная система регуляции -- являются двумя аспектами
   единой системы нейрогуморальной регуляции целостных функций
   организма.

   #+BEGIN_QUOTE
   Условность деления на нервные и гуморальные механизмы регуляции
   функции проявляется уже в том, что нервный импульс передается с
   клетки на клетку с помощью гуморального сигнала -- в нервном
   окончании выделяются молекулы нейромедиатора, который является
   гуморальным фактором.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Нервный контроль отсутствует у двух органов: коры надпочечников и
   плаценты.
   #+END_QUOTE

*** Различия между нервной и гуморальной регуляцией

    Основные отличия нервной регуляции от гуморальной следующие:
    нервный сигнал целенаправленный; нервный сигнал быстрый; нервный
    сигнал краткий.

    #+BEGIN_QUOTE
    Межполушарная ассиметрия -- различия в записи ЭЭГ на левой и
    правой половине головы -- формируется в результате организующего
    влияния половых гормонов.
    #+END_QUOTE

*** Функциональная классификация гуморальных факторов

    Гормоны -- биологические вещества, синтезируемые специальными
    клетками, секретируемые во внутреннюю среду, транспортируемые с
    током крови по всему организму и изменяющие функции
    тканей-мишеней.

    Клетки, секретирующие гормоны, образуют железы внутренней
    секреции, которые все вместе образуют эндокринную систему.

    "Внутренняя секреция" означает, что вещества выделяются в кровь
    или в другую внутреннюю жидкость; "внешняя секреция" означает, что
    вещества выделяются в пищеварительный тракт или на поверхность
    кожи.

** Основные гормоны и железы

*** Гипоталамо-гипофизарная система

    Гипоталамус является высшим отделом эндокринной системы. Эта
    стуруктура головного мозга, получая и перерабатывая информацию об
    изменениях в мотивационных системах, изменениях во внешней среде и
    во внутренних органах, изменениях гуморальных констант организма,
    интегрирует полученную информацию в виде изменения синтеза
    многочисленных гормонов, управляющих активностью эндокринной
    системы организма.

    В соответствии с возникающими потребностями организма гипоталамус
    модулирует активность эндокринной системы, управляя функциями
    гипофиза.

    Модуляция (т.е. активация или торможение) осуществляется путем
    синтеза и секреции специальных гормонов -- релизингов (release --
    выделять), которые, поступая в специальную (портальную)
    кровеносную систему, транстортируются в переднюю долю гипофиза. В
    передней доле гипофиза гипоталамические гормоны стимулируют или
    тормозят синтез и секрецию гипофизарных гормонов, которые
    поступают в общий кровоток.

    Часть гипофизарых гормонов является тропными (tropos --
    направление) гормонами, т.е. они стимулируют секрецию гормонов из
    перефирических желез: коры надпочечников, гонад (половых желез) и
    щитовидной железы.

    Гипофизарных гомонов, тормозящих функции перефирических желез, не
    существует.

    Другая часть гипофизарных гормонов действует не на переферические
    железы, а непосредственно на органы и ткани.

    Перефиричесие гормоны, взаимодействуя с гипофизом и гипоталамусом,
    тормозят по методу обратной связи секрецию соответствующих
    гипоталамических и гипофизарных гормонов.

    По химической природе все гипоталамические и гипофизарные гормоны
    являются пептидами, т.е. состоят из аминокислот.

    Все гипоталамические гормоны, помимо эндокринных функций, обладают
    выраженным психотропным эффектом.

    В отличие от гипоталамических, не все гипофизарные гомоны обладают
    психотропным действием.

*** Гипоталамические и гипофизарные гормоны

*** Вазопрессин и окситоцин

    Вазопрессин и окситоцин -- эти гормоны синтезируются в
    гипоталамусе, в заднем гипофизе выделяются в общий
    кровоток. Задний гипофиз образован окончаниями отростков нервных
    клеток гипоталамуса.

*** Периферические гормоны

    В поджелудочной железе синтезируются инсулин и глюкагон.

    В щитовидной железе синтезируются тироксин и трийодтиронин.

    Секреция гормонов щитовидной железы мало меняется при изменении во
    внешней или внутренней среде. В норме гормоны щитовидной железы
    осуществляют только тоническое влияние на функции организма.

    В мозговом слое надпочечников синтезируются адреналин и норадреналин.

*** Стероидные гормоны

    Пептиды:

    - быстрый выброс в кровь (секунды)
    - короткое время полураспада (1-2 минуты)
    - распад осуществляется ферментами крови
    - с трудом проникают в ЦНС
    - разрушаются пищеварительными ферментами (неэффективны при
      пероральном введении)

    Стероиды:
    
    - медленный выброс в кровь (несколько минут)
    - короткое время полураспада (десятки минут)
    - распад осуществляется главным образом в печени
    - легко проникают в ЦНС
    - всасываются в кровь в желудочно-кишечном тракте

    Стероиды синтезируются из общего предшественника -- холестерина и
    делятся на пять семейств:

    - глюкокортикоиды
    - минералкортикоиды
    - прогестины
    - андрогены (мужские половые гормоны)
    - эстрогены (женские половые гормоны)
 
    Стероидные гормоны синтезируются в двух железах: коре
    надпочечников и гонадах.  

    #+BEGIN_QUOTE
    Адаптивное значение глюкокортикоидов было показано Гансом Селье в
    1930-е годы. Уже в годы Второй мировой войны экстракты коры
    надпочечников использовались в немецкой армии в качестве
    стимуляторов (например, летчиками перед пикированием). Материал --
    бычьи надпочечники -- вывозили подводным лодками из Аргентины.
    #+END_QUOTE

*** Мелатонин

    В эпифизе синтезируется мелатонин.

    Особенностью регуляции функций эпифиза является прямая связь с
    гипоталамическими ядрами, непосредственно связанными с
    сетчаткой. Таким образом, эпифиз получает от глаз сигналы об
    изменении освещенности. Секреция эпифизарных гормонов усиливается
    в темноте.

** Принципы гормональной регуляции

*** Передача гормонального сигнала: синтез, секреция, транспорт гормонов, их действие на клетки-мишени и инактивация

    Реализация гормонального сигнала происходит в пять этапов:

    1) синтез

    2) секреция

    3) транспорт

       Связанный транспортными белками гормон биологически не активен.
       
    4) взаимодействие с клеточным рецептором

       Клеточные рецепторы -- сложные белки. Специфичность больше, чем
       у транспортных белков.

       Связывание гормона с рецептором вызывает биохимические реакции,
       итог которых заключается в изменении синтеза определенных белков.

    5) инактивация и вывод из организма

    Биологическая активность эндокринной системы может меняться
    несмотря на то, что содержание гормона в крови может оставаться
    неизменным. Изменения связаны с изменениями в транспорте,
    рецепции, или катаболизме молекул гормона.
       
    #+BEGIN_QUOTE
    Длительный прием оральных контрацептивов приводит к нарушению
    либидо. У таких женщин обнаружено повышенное содержание
    транстортного белка -- глобулина, связывающего эстрогены.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Для прерывание беременности на ранних сроках применяются вещества,
    нарушающие связывание прогестрона с его клеточными рецепторами.
    #+END_QUOTE

*** Поливалентность гормонов

    Каждый гормон действует на многие органы и ткани.

*** Регуляция по механизму отрицательной обратной связи и гормональные влияния на психику

    Гормоны тормозят собственную секрецию по механизму отрицательной
    обратной связи.

    Количество рецепторов в тканях-мишенях уменьшается при длительном
    увеличении концентрации гормона в крови.

    Психотропный эффект гормона зависит от скорости изменения
    концентрации гормона в крови, а не от абсолютного значения этой
    концентрации.

*** Взаимодействие эндокринных систем: прямая связь, обратная связь, синергизм, пермиссивное действие, антагонизм

    Существует пять типов взаимодействия эндокринных систем:

    - один гормон стимулирует синтез другого
    - один гормон тормозит синтез другого
    - два гормона оказывают схожий эффект (синергизм)
    - один гормон усиливает действие второго, хотя сам не оказывает
      влияния на данную функцию (пермиссия)
    - два гормона оказывают на клетки организма противоположный эффект
      (антагонизм)

*** Механизмы гормональных влияний на поведение

    Гормоны могут влиять на поведение пятью способами:

    1) влияя на состояние переферических органов

       - серотонин, действуя как гормон, вызывает зуд
       - тестостерон делает кожу на головке пениса тоньше, что
         повышает чувствительность

    2) влияя на обмен веществ в ЦНС

       - кортизол усиливает транспорт глюкозы к клетки мозга

    3) влияя на медиаторы в ЦНС

    4) влияя на состояние переферической нервной системы

    5) влияя на строение ЦНС

       - под влиянием эстрогенов увеличивается количество межнейронных
         контактов
       - глюкокортикоиды вызывают гибель клеток в ЦНС
       - минералкортикоиды увеличивают стабильность нейронов некоторых
         стуруктур мозга

** Обмен углеводов

*** Значение углеводов

    Углеводы являются основным источником энергии для клеток, а для
    нервных элементов -- единственным.

    Глюкоза -- единственный и незаменимый источник энергии для клеток
    ЦНС, т.е. головного и спинного мозга.

    #+BEGIN_QUOTE
    При умеренном климате на энергетические нужды используется
    приблизительно две трети поступающих питательных веществ.
    #+END_QUOTE

    #+BEGIN_QUOTE
    В средневековой Европе сахар продавался в аптеках.
    #+END_QUOTE

*** Психотропный эффект углеводов

    Начальный этап любого стресса вызывает подъем уровня концентрации
    глюкозы в крови.

    Недостаток глюкозы ухудшает формирование памяти.

    Ухудшение памяти при дефиците глюкозы связано с недостаточным
    снабжением глюкозой клеток ЦНС.

*** Содержание глюкозы в крови -- важнейшая константа

    Нормальным считается содержание глюкозы от 4.4 до 6.6 милимолля,
    что соответствует приблизительно 1 грамму на литр крови.

    Падение содержания глюкозы в крови гораздо опаснее, чем рост этого
    показателя.

    Концентрация глюкозы в крови уменьшает только один гормон --
    инсулин, а повышают -- несколько гормонов.

    Концентрация глюкозы в крови постоянно поддерживается в
    определенных узких границах. Выход за эти границы субъективно
    ощущается как ухудшение самочувствия.

    Чувство голода возникает в результате поступления в мозг сигналов
    о снижении концентрации глюкозы в крови и нервных сигналов от
    пустого желудка.

    #+BEGIN_QUOTE
    Выкуривание одной сигареты приводит к повышению уровня глюкозы
    примерно на 0.5% исходного уровня.
    #+END_QUOTE

*** Гуморальные влияния на различные этапы обмена углеводов

    Гормоны регулируют все этапы углеводного обмена: переваривание
    пищи, всасывание в кровь, расходование углеводов и создание запаса
    энергоносителей.

    В организме постоянно идут процессы гликогенеза -- синтеза
    гликогена из глюкозы, гликогенолиза -- распада глюкогена до
    глюкозы и глюконеогенеза -- синтеза глюкозы из жиров, белков и
    молочной кислоты.

    Алкоголь тормозит глюконеогенез, что приводит к значительному
    снижению (до 30%) содержания глюкозы в крови.

    Глюкокортикоид кортизол -- единственный гормон человека, который
    увеличивает транспорт глюкозы в клетки головного мозга.

    Энергия клетки ЦНС получают только в результате окислительного
    фосфорилирования.

*** Метаболическая и гедонистическая функция углеводов

    Углеводы настолько важны для функций организма, что у всех
    млекопитающих, включая человека, сформировался механизм
    гедонистического эффекта углеводов: вкус углеводов им
    приятен. Этим обеспечивается постоянное поступление углеводов с
    диетой.

    #+BEGIN_QUOTE
    Hic habitat felicitas -- "здесь обитает счастье" -- надпись на
    стене кондитерской.
    #+END_QUOTE

** Комплексный пример психотропного эффекта гормонов: предменструальный синдром

   Предменструальный синдром -- это многообразные аффективные
   расстройства, проявляющиеся или усиливающиеся в конце
   менструального цикла.

   Предменструальный синдром обусловлен резким падением секреции
   прогестерона в конце менструального цикла.

   #+BEGIN_QUOTE
   Большинство самоубийств, совершаемых женщинами, происходит на фоне ПМС.
   #+END_QUOTE

   #+BEGIN_QUOTE
   Метаболиты прогестерона обладают противотревожным и успокающиваим
   действием, подобным тому, которые оказывают распространненые
   транквилизаторы типа седуксена, диазепама, тазепама,
   феназипама. Это объясняется тем, что метаболиты прогестерона и
   дезоксикортикостерона связываются с теми рецепторами в ЦНС, что и
   бензодиазепиновые транквилизаторы.
   #+END_QUOTE

*** Влияние контрацептивов

    Предменструальный синдром усиливается при приеме контрацептивов,
    содержащих синтетические прогестины, которые не образуют
    анксиолитических метаболитов и снижают эндогенный прогестерон по
    механизму отрицательной обратной связи.

*** Влияние избытка соли в диете

    Предменструальный синдром усиливается при избытке соли в диете,
    т.к. снижается секреция дезоксикортикостерона, образующего
    анксиолитические метаболиты.

*** Влияние пищевых углеводов

    Предменструальный синдром может усиливаться при недостатке
    углеводов в диете из-за падения концентрации глюкозы в крови и
    недостаточного снабжения ЦНС глюкозой.

    Предменструальный синдром может училиваться при избытке
    низкомолекулярных углеводов в диете из-за падения концентрации
    глюкозы в крови, если система секреции инсулина слишком
    чувствительна к уровню глюкозы.

    #+BEGIN_QUOTE
    Снижение глюкозы в крови после приема сахарозы обусловлено
    повышенной реактивностью поджелудочной железы.
    #+END_QUOTE

*** Влияние алкоголя

    Предменструальный синдром усиливается при приеме алкоголя.

    #+BEGIN_QUOTE
    В отсутствие поступления углеводов с пищей, глюконеогенез
    становится критическим процессом, поддерживающим необходимый
    уровень глюкозы в крови, поскольку запасы глюкогена в печени
    относительно невелики.
    #+END_QUOTE

* Стресс

** Понятие стресса

   Стресс -- это неспецифичная системная приспособительная реакция
   организма на отклонение условий существования от привычных.

*** Неспецифичность стресса

    Неспецифичность стресса состоит в том, что одну и ту же реакцию
    организма вызывают различные раздражения независимо от их природы.

    Стрессорная реакция не зависит от модальности стимула.

    Именно неспецифичность стала в свое время наиболее революционной
    чертой концепции стресса.

*** Системность стресса

    Системность стресса состоит в том, что реагируют сразу все системы
    организма.

*** Адаптивность стресса

    Адаптивность стресса состоит в том, что эта реакция направлена на
    приспособление к изменившейся внешней или внутренней среде.

*** Новизна изменений

    Стресс -- это реакция на непривычные изменения среды, а не на
    любые, или сильные или вредные для организма.

    Уровень стресса никогда не бывает нулевым, т.к. в любой ситуации
    имеется элемент новизны.

    #+BEGIN_QUOTE
    [речь о Питере] Например, вечером после напряженного дня приятно
    остановиться в вестибюле Пушкинской у выцарапанного на мраморе
    слова "Туся", существующего едва ли не со дня открытия станции.
    #+END_QUOTE

** Стресс сопровождает и приятные события

   Многие приятные события сопроводаются стрессом. Классический пример
   положительного стресса -- воздействие на человека произведений
   искусства.

   #+BEGIN_QUOTE
   Благодаря лексической бедности и примитивной грамматике книги Жоржа
   Сименона и Агаты Кристи полезны для начинающих изучать иностранные
   языки.
   #+END_QUOTE

** Определение величины стресса

   Стрессорная реакция организма характеризуется четырьмя
   показателями:

   - чувствительность
   - реактивность
   - скорость развития
   - скорость угасания

   Поскольку стресс является системной реакцией, т.е. при стрессе
   происходят изменения во всех системах организма, то в качестве
   примера можно рассматривать любую реакцию: изменение частоты
   сердечных сокращений, кожно-гальваническую реакцию, изменение
   количества стереотипных движений, изменение уровня гормонов и пр.

*** Чувствительность

    Чувствительность организма к воздействию определяется минимальной
    силой раздражителя, которая вызывает реакцию. Эта минимальная сила
    раздражителя называется порогом реакции.

    Чем больше сила раздражителя, при которой возникает реакция, тем
    выше порог реакции и тем меньше чувствительность организма.

    Один из физиологических регуляторов чувствительности --
    беременность. У беременных чувствительность к болевым стимулам
    падает в несколько раз.

*** Реактивность

    Реактивность организма характеризуется степенью изменения
    определяемого параметра после предъявления стимула.

*** Скорости развития и угасания реакции

    Количественно скорость изменения любой реакции определяется так
    называемой постоянной времени -- временем, за которое реакция
    достигает 63% от максимального значения. Значение 63% выбрано из
    математических соображений, поскольку математический аппарат лучше
    всего разработан для экспоненциальных функций, которые
    используются для описания изменений в системах.

    Скорость угасания реакции количественно определяется обратной
    величеной -- временем, необходимым для того, чтобы показатель,
    возвращаясь к исходному значению, достиг 37% от максимума.

    Постоянная времени угасания может стресса может не зависеть от
    постоянной времени нарастания. Остальные характеристики
    стрессорной реакции, в общем случае, также не зависят друг от
    друга.

*** Устойчивость к стрессорным ситуациям -- это скорость угасания стрессорной реакции

    Устойчивость любой системы -- это скорость возвращения в исходное
    состояние.

    Показатель устойчивости к стрессу -- скорость угасания стрессорной
    реакции.

    Не существует гормона, торямозящего стрессорную
    реакцию. Единственным механизмом торможения стресса является
    отрицательная обратная связь в гипофиз-адреналовой системе.

** Поведение при стрессе

   Изменения в среде вызывают определенную потребность, для
   удовлетворения которой человек или животное должны либо
   попытаться возвратить среду к прежнему состоянию, либо
   приспособиться к новым условиям существования. Для
   удовлетворения потребности формируется мотивация,
   т.е. активизируется память о способах удовлетворения данной
   потребности. В памяти человека или животного хранится множество
   программ действия, но каждая из этих программ наиболее
   эффективна для строго определенных изменений среды. Поэтому в
   рамках мотивации происходит интенсивный сбор
   информации. Собирается в первую очередь информация, которая
   позволит охарактеризовать новую ситуацию как знакомую,
   т.е. такую в которой организм уже действовал и удовлетворил
   имевшуюся потребность.

   Совокупность черт измененного состояния среды, которая позволяет
   характеризовать ситуацию как знакомую, называется пусковым
   (ключевым) стимулом.

   Если найти ключевой стимул не удается, т.е. новизна ситуации
   велика, то у организма развивается стресс -- неспецифическая,
   системная адаптационная реакция на отклонение условий существования
   от привычных. Поведенческим компонентом стрессорной реакции
   является смещенная активность.

*** Универсальная форма поведения при стрессе -- смещенная активность

    При смещенной активности энергия, накопленная внутри одной
    мотивации, разряжается в виде фиксированного комплекса действий
    другой мотивации.

    Признаки смещенной активности:

    - отсутствие биологической целесообразности
    - возникновение в отсутствие пусковых стимулов для данного ФКД
    - использование форм поведения специфичных для данного вида (у
      человека, как правило, наиболее привычные формы поведения)

    Если поведение животного характеризуется этими тремя признаками,
    значит это смещенная активность, следовательно субъект испытывает
    стресс.

    Смещенная активность возникает:

    - когда не найден ключевой стимул, иными словами, когда животное
      не знает как поступить

    - при конкуренции двух ФКД в рамках одной мотивации 

      Пример: противостояние двух петухов. Один из них начинает
      клевать почву, хотя зерен на на земле нет. Он не может выбрать
      между бегством, нападением и демонстрацией подчинения сопернику.

    - при столкновении мотиваций

*** Формы смещенной активности

    - Мозаичная активность -- поведение, состоящее из фрагментов
      различных ФКД. 

      Мозаичной в стрессовой ситуации становится не только
      двигательная, но и психическая активность.

    - Переадресованное поведение -- если какая-то форма поведения не
      может быть реализована в контакте с конкретным человеком, она
      осуществляется в процессе общения с другим человеком или
      предметом. Переадресованным бывает только социальное поведение.

    - Собственно смещенная активность -- использование ФКД другой
      мотивации, явно неадекватной для удовлетворения текущей
      последовательности. Чаще всего смещенное поведение имеет форму
      наиболее привычного для данного субъекта вида активности.

      Поэт пишет стихи, художник рисует, если их что-то взволнует,
      поскольку это привычная для них форма активности.

      Кроме агрессивного, в качестве смещенного может выступать любое
      поведение. Очень часто это половое поведение.

      Не только невозможность реализации половой мотивации приводит к
      другим, неполовым формам поведения (сублимация), но и половое
      поведение часто является результатом невозможности реализации
      других, неполовых мотиваций.

      Еда, агрессия и секс -- распространенные формы смещенной
      активности.

    #+BEGIN_QUOTE
    Непрекращающиеся вооруженные конфликты ведут к тому, что в
    гражданское общество постоянно вливаются молодые люди, для
    которых убийство -- привычная форма активности. Следует
    подчеркнуть, что опастность для общества они представляют не
    потому, что их учили убивать. Любой врач знает о том, как убить
    человека гораздо больше, чем сержант морской пехоты. Но для
    демобилизованного спецназовца убийство или насилие -- это
    привычный способ реагирования на любые изменения в окружающей
    среде, причем один из немногих, в силу его молодости, имеющихся
    у него стереотипов поведения.
    #+END_QUOTE

*** Груминг -- смещенная активность, в которой сочетаются эндокринный и поведенческий компоненты стресса

    Груминг -- форма собственно смещенной активности и, одновременно,
    форма поведения, которая уменьшает психическое напряжение.

    Груминг вызывается не только ситуационными изменениями, но и
    определенными гуморальными факторами -- гипофизарными стрессорными
    гормонами. 

    Груминг приводит к росту концентрации эндорфинов в крови.

** Гормоны при стрессе

   Глюкокортикоиды регулируют основную адаптивную функцию
   организма. Их главная функция -- усиление сопротивляемости
   организма при длительном действии стрессора.

   С другой стороны, длительная избыточная концентрация
   глюкокортикоидов в крови ведет к возникновению заболеваний.

   Не существует гормона, который тормозит стрессорную
   реакцию. Единственным механизмом торможения стрессорной реакции
   является механизм обратной связи.

** Психотропные эффекты стрессорных гормонов

   Все стрессорные гормоны обладают психотропным эффектом.

   Стресс приводит к изменению зависимости между харектеристиками
   стимула и реакцией. Закономерности функционирования организма,
   выявленные в покое, меняются при стрессе. Психотропные свойства
   гормонов зависят от уровня стресса.

*** Кортиколиберин

    Кортиколиберин индуцирует чувство тревоги.

    Большая часть поведенческих эффектов кортиколиберина соответствует
    разнообразным изменениям в первый период стрессорной реакции,
    общим знаменателем которых является увеличение уровня тревоги, что
    обеспечивает готовность организма к приспособлением в среде,
    вызвавшей стресс.

    Кортиколиберин подавляет синтез гонадолиберина, что проявляется в
    форме торможения всех форм половой активности. Длительное
    воздействие стрессора ведет к нарушениям половой сферы.

*** АКТГ

    АКТГ усиливает внимание и улучшает память.

    АКТГ представляет собой пептид, т.е. цепочку аминокислот. Разные
    участки этой цепочки обладают разными свойствами. Вводя животному
    или человеку определенный фрагмент АКТГ, экспериментатор
    региструет изменение функций только одного органа, или одной
    функции.

    АКТГ улучшает не обучение вообще, а только за счет усиления
    внимания к зрительной и слуховой информации.

    Эффекты АКТГ зависят от пола испытуемого. У мужчин АКТГ снижает
    тревожность, а у женщин увеличивает, при введении в середине
    менструального цикла -- увеличивает. АКТГ при введении женщинам
    ухудшал зрительное внимание и улучшал вербальную память.

*** Окситоцин и вазопрессин

    Окситоцин снижает тревогу, ослабляет память, усиливает аффиляцию.

    В клинике используется при лечении неврозов. Поскольку окситоцин
    только модулирует, но не индуцирует все вышеперечисленное, это
    эффективно только совместно с психотерепией.

    Вазопрессин повышает тревогу и усиливает реакцию затаивания.

    #+BEGIN_QUOTE
    При шизофрении увеличена активность систем окситоцина и снижена
    активность систем вазопрессина.
    #+END_QUOTE

*** Эндорфины и энкефалины

    Энфорфины и энкефалины уменьшают чувство боли и вызывают эйфорию.

    Именно с выделением эндорфинов и энкефалинов при стрессе связана
    тяга к занятиями экстремальными видами спорта.

    Попытки создать эффективный анальгетик, который не был бы
    эйфориаком, пока безуспешны.

*** Анреналин

    Анреналин усиливает физиологические изменения, подготавливающие
    организм к реакции "борьбы или бедствия".

*** Гормоны коры надпочечников

    Основная психотропная функция глюкокортикоидов -- обеспечение
    реакции затаивания.

    #+BEGIN_QUOTE
    Еще одним примером неопределенной мотивации испытуемого является
    ухудшение тестов при неоднократном предъявлении одной и той же
    задачи. Если человек или животное быстро решает предложенную
    задачу, то при последующих предъявлениях этого теста процент
    успешных решений значительно снижается. Если задача сложна для
    испытуемого, то процент правильных решений монотонно
    нарастает. Л.В. Крушинский предположил, что чнижение процента
    правильных решений связано с неврозоподобным состоянием,
    развивающимся у успешно решающих задачу в следствие сильного
    напряжения нервно-психических функций. Но возможно, что у
    испытуемого меняется мотивация. Решение конкретной задачи не
    представляет для него интереса, и он начинает экперементировать со
    средой.
    #+END_QUOTE

* Неконтролируемый стресс и депрессия

  При депрессии угнетены аффективные, когнитивные и моторные функции.

  Наличие больных родственников (наследственный фактор) существенно
  увеличивает риск заболевания.

  Основной фактор внешней среды, который влияет на формирование
  депрессии, -- неконтролируемый стресс.

** Понятие неконтролируемого стресса

   Стресс, возникающий несмотря но то, что
   физические характеристики стимула остаются неизменными (нет эффекта
   новизны стимула). Возникает если выполняется хотя бы одно (или
   несколько) условий:
  
   - невозможно приспособиться к воздействию
   - невозможно избавиться от воздействия
   - невозможно избежать воздействия
   - невозможно предсказать начало воздействия
   - невозможно предсказать конец воздействия

*** Эксперемент Шенгер-Крестовниковой

    В лаборатории И.П. Павлова его сотрудница
    Н.Р. Шенгер-Крестовникова обучала собаку отличать круг от эллипса,
    постепенно изменяя форму эллипса так, чтобы он все больше и больше
    походил на круг. Правильное решение подкреплялось пищей,
    неправильное -- не подкреплялось. Когда соотношение осей эллипса
    достигло 8:9, собака стала ошибаться и не смогла научиться
    различать фигуры даже за три недели, а затем у нее внезапно
    пропала способность различать даже вытянутый эллипс и круг. Более
    того, пропали все условные рефлексы, выработанные прежде. Кроме
    того "собака, ранее спокойно стоявшая в станке, теперь была
    постоянно в движении и повизгивала. Стимулы, которых животное
    старалось избегать (аверсивные -- боль, голод) не
    применялись. Единственным фактором, травмировавшим психику
    животного, оказалась невозможность установить контроль над
    ситуацией.

    Неконтролируемые воздействия вызывают нарушения всех трех функций
    психики: когнитивной, моторной и аффективной.

*** Различные способы создания неконтролируемой ситуации

    Одинаковое по своим физическим характеристикам воздействие
    вызывает различную реакцию человека или животного в зависимости от
    возможности контролировать это воздействие.

    Только у тех животных или людей, которые подвергались
    неконтролируемому воздействию, развивались многочисленные
    расстройства, в отличие от испытавших такие же болевые
    воздействия, но в контролируемых условиях.

    Выученная беспомощность -- агедония, вызванная неконтролируемым
    стрессом.

    Выученная беспомощность -- это прежде всего аффективное
    нарушение. 

    Выученная беспомощность не является прерогативой высших
    животных. Оно было выработано у многих млекопитающих, птиц, рыб, и
    даже тараканов и улиток. Это означает, что процессы, лежащие в
    основе депрессивных расстройств человека, общие для всех живых
    существ. 

    Некоторые способы создания неконтролируемых ситуаций:

    - неконтролируемый доступ к витальным ресурсам
    - социальное давление
    - лишение возможности двигаться

    #+BEGIN_QUOTE
    В экспериментах широко используется такое, казалось бы мягкое
    воздействие, как лишение возможности двигаться. Для этого крыс и
    мышей помещают в пластиковые стаканчики.
    #+END_QUOTE

** Практическое значение неконролируемого стресса

   Практическое значение неконтролируемого стресса заключается в том,
   что подведение подвергшегося ему животного или человека становится
   управляемым.

   Создание неконтролируемых стрессорных ситуаций для формирования
   выученной беспомощности широко используется в человеческом обществе
   с целью повышения управляемости как отдельных людей, так и больших
   групп населения.

   Основное поле применения неконтролируемых ситуаций это, это конечно
   же, социальные отношения. Психологи-практики уже в доисторические
   времена поняли значение этого феномена. Не случайно во многих
   религиях в том или ином виде имеется постулат о греховности
   удовольствий, потребность в которых является одной из жизненно
   необходимых т.е. витальных. Благодаря этому императиву каждый
   человек оказывается виноватым перед Богом. А постоянное чувство
   если не вины, то возможности наказания делает человека управляемым.

   Один из ярких примеров выработки выученной беспомощности у больших
   групп людей -- "трудовые лагеря" фашисткой Германии. Их задачей
   было перевоспитание личности, которое проводилось с помощью
   непредсказуемого стрессорного воздействия. Правила внутреннего
   распорядка постоянно менялись, о чем не сообщалось заключенным. При
   этом любое нарушение этих правил каралось. Кроме этого, достаточно
   грубого приема, применялась "иррационализация": заключенных
   заставляли делать действия, лишенные какого-либо смысла. Например,
   не только рыть ямы и тут же засыпать их, что можно было бы
   объяснить садизмом конкретного охранника, но и попросту регулярно
   выслушивать правила внутреннего распорядка, которые и так были
   вывешены на каждом углу. В результате, подобно собаке
   Шенгер-Крестовниковой, заработавшей невроз в постоянных попытках
   понять законы окружающего мира, заключенные всего за несколько
   месяцев выучивались беспомощности. Они выходили на свободу новыми
   людьми -- лишенными собственной жизненной энергии и, следовательно,
   легко управляемыми. 

   Именно отсутствие какой-либо причинно-следственной связи между
   поведением объекта и непрятным для него воздействием и является
   непременным условием того, чтобы ситуация стала
   неконтролируемой. Если наказание, пусть даже весьма суровое, будет
   следовать строго за определенными поступками, то субъект научится
   избегать таких поведенческих форм, но общая управляемость его
   поведения не увеличится, т.к. сформируется не выученная
   беспомощность, а условный рефлекс избегания определенных ситуаций.

   Если человек пытается справиться с ситуацией, точнее, изменить
   неблагоприятный ход событий, значит, у него пока еще не
   сформировалась выученная беспомощность.

   Если неконтролируемому воздействию подвергаются дети, то симптомы
   выученной беспомощности могут сохранятся десятилетиями.

   #+BEGIN_QUOTE
   Только романтические ослы ищут загадки, тайны, сюжеты и чудеса в
   мирах непознанного и непостижимого; нет ничего более таинственного,
   загадочного и потрясающего воображение, чем мир советстких законов
   и установлений... (Витицкий С., Поиск предназначения, или Двадцать
   восьмая теорема этики)
   #+END_QUOTE

** Депрессия и тревога

*** Различия между депрессией и тревогой

    Тревога -- аффект, возникающий в ожидании неопределенной опасности
    или неблагоприятного развития ситуации. Внимание тревожного
    субъекта направленно в будущее на источник тревоги.

    Депрессия -- синром с торможением аффективной (ведущий симптом), когнитивной и
    моторной функций. Внимание субъекта при депрессии направлено в
    безрадосное настоящее.

    Тревога сопровождает начальные этапы хронического стресса, а
    депрессия формируется в результате длительного неконтролируемого
    стрессорного воздействия.

    Если в жизни человека развитию депрессии предшествовала
    психическая травма, то депрессию называют реактивной (от слова
    реакция). Если сильного потрясения не выявлено, то депрессия
    считается эндогенной. Эндогенная депрессия развивается в
    результате множества собитий, каждое из которых сопровождалось
    небольшим стрессом.

    Хронический умеренный стресс -- адекватная модель эндогенной
    депрессии, развившейся в результате множества слабых стрессоров.

    Депрессия, как правило, сопровождается жалобами на боли в разных
    участках тела и расстройств различных систем организма. Это так
    называемые соматические маски депрессии.

    По тяжести расстройста, депрессия может являться психозом или
    оставаться на уровне невротического расстройства. При психозе
    больной выключается из социальной жизни и нуждается в
    госпитализации. При неврозе больной может выполнять многочисленные
    функции члена общества.

    Деприсивные эпизоды могут, но не обязательно перемежаться
    маниакальными эпизодами. Монополярная депрессия как правило
    протекает легче биполярной.

    Тревогу делят на первичную (посттравматический синдром) и
    вторичную (входящую в депресивный синдром). Для их различения
    применяют диазепамовый тест. Диазепам -- противотревожный
    препарат, который не имеет антидепрессивной активности.

    #+BEGIN_QUOTE
    М.М. Зощенко страдал депрессивным психозом. В романе "Перед
    восходом солнца", законченном в 1944 году, Зощенко перебирает
    события своей жизни, пытаясь объяснить свои частые приступы
    дурного настроения. Среди прочего он вспоминает и свое ухаживание
    за девушкой, которая во время прогулок заходила к модистке, а его
    просила подождать на улице. Через какое-то время девушка выходила
    и молодые люди продолжали гулять. Спустя некоторое время герой
    романа узнает, что девушка посещала не модистку, а любовника. На
    недоуменный вопрос девушка ответила: "Что же делать... Я была так
    влюблена в вас, а мы только гуляли по улицам." Анализируя подобные
    события Зощенко пытается убедить читателя (и себя самого), что
    подобные события -- это пустяки. Этот и множество других подобных
    случаев не могут быть причиной его почти постоянно дурного
    самочувствия и плохого настроения. В доказательство писатель
    приводит разные аргументы, ссылается на многочисленные примеры
    силы человеческого духа, уверяет, что поведение человека
    определяется его волей и разумом. Не смотря на это Зощенко не смог
    путем рационализации побороть свою болезнь.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Частота конкретных соматических проявлений депрессии различна в
    разных социальных группах и изменяется с течением времени. Это
    связано с тем, что психосоматические симптомы, как многие
    психические расстройства, имеют эпидемический характер
    распространения, обусловленный бессознательным
    подражанием. Например, термин "ипохондрия", который означает
    сосредоточенность на вопросах своего здоровья, переводится с
    греческого как "подреберье". Мы делаем вывод, что античные
    ипохондрики жаловались главным образом на неопределенные
    болезненные ощущения в верхней части живота. Высокая частота такой
    локализации болей при депрессии отразилась в виде такого синонима
    депрессии как "сплин". Это английское название селезенки, которая
    расположена в левом подреберье.
    #+END_QUOTE

*** Гормоны и депрессия

    Гуморальный фактор депрессии неизвестен, хотя есть факты,
    указывающие на существование такого вещества.
    
    При депрессии нарушены реакции многих эндокринных систем.

    Развитие депрессии связано с длительным увеличением активности
    гипофиз-адреналовой системы, т.е. устойчиво повышенной секреции
    всех стрессорных гомонов: кортиколиберина, АКТГ и кортизола.

    При этом:

    * снижается секреция тропинов в ответ на либерины
      - снижается секреция АКТГ в ответ на введение кортиколиберина
      - снижается секреция тиреотропина в ответ на введение
        тиреолиберина
    * снижается секреция желез в ответ на тропины
    * нарушается механизм отрицательной обратной связи
      - количество кортизола в крови не падает при введении
        глюкокортикоидов (дексаметазоловый тест)
    * уменьшает количество рецепторов
      - снижается падение сахара в крови при введении инсулина
        (инсулиновый тест)
    * появляются альтернативные механизмы регуляции
      - увеличина секреция кортизола в ответ на введение вазопрессина
        (вазопрессин не регулируется по механизму отрицательной
        обратной связи, что позволяет выжимать из организма больше
        кортизола)

    Каждый из вышеприведенных эффектов, взятый по отдельности, мало
    репрезентативен при диагностике, но в сумме они дают точность до
    90%.

    Гонадолиберин и эндогенные опиаты являются естественными
    антидепрессантами.

    #+BEGIN_QUOTE
    Послеродовая депрессия связана с резким падением уровня
    прогестерона в крови.
    #+END_QUOTE

*** Методы защиты от неконтролируемого стресса

    Существуют методы психофизиологической коррекции депрессивных
    состояний и преодоления негативных последствий неконтролируемого
    стресса.

    * Перевод в сферу сознания своих потребностей, мотиваций и
      собственного типа личности.

    * Субъективное восприятие ситуации как контролируемой
      предотвращает развитие депрессии. Чтобы уйти из-под прессинга
      неконтролируемой ситуации нужно делать все, что не запрещено.

    * Создание параллельных социальных структур (при хроническом
      социальном неконтролируемом стрессе). Для удовлетворении
      потребности в самоидентификации, нужно найти сообщество, в
      котором человек не будет испытывать постоянных
      поражений. Сообщество может быть и метафизическим, в частности
      реально состоящим только из одного человека. Простейший метод
      создания метафизического сообщества -- чтение сериальной
      литературы.

    * Мышечная работа.

    * Лишение сна. Механизм неизвестен, но эффективен. Возможно он
      связан с физическими нагрузками, а так же с секрецией
      гонадолиберина, которая растет при повышенной
      освещенности. Депрессия ослабляется, если смотреть на яркую
      лампу или находиться в освещенном помещении. 

    * Алкоголь. Алкоголь является стресс-протективным средством, но
      не антидепрессантом. Прием алкоголя сразу после
      неконтролируемого стресса предотвращает развитие депрессивных
      состояний. Поскольку основной вред здорою наносит стресс
      повседневности (воздействие множества мелких, незначительных по
      отдельности стрессоров) Бехтерев и Юнг рекомендавали
      переодическое, но не регулярное употребление небольших доз
      алкоголя. В полярных экспедициях алкоголь выдают в любых количествах при
      гибели людей, но именно в день трагического проишествия, а не на
      следующий и ни в один из последующих дней.

*** Биологический смысл депрессивных состояний

    Депрессия -- это чрезмерное развитие адаптивной реакции
    затаивания.

    Субдепрессивные состояния благопрятны для умственной работы.

* Психологические типы

  Психологические тип (в отличии от характера и темперамента) в
  наибольшей степени определяются врожденными особенностями и поэтому
  тесно связан с соматическими признаками.

** Общие представления о типологизации

*** Синтетические и аналитические системы

    Системы психологических типов строятся на основе одного из двух
    принципов: синтетического (описание целостных типов) и
    аналитического (выделение нескольких простых свойств психики,
    разная выраженность которых создает неприрывный континуум типов)
    Использование синтетического подхода часто называется
    типологическим подходом, а исполользование аналитического --
    структурным.

    #+BEGIN_QUOTE
    Поклонники античной философии легко узнают в типологическом
    подходе школу Аристотеля, любителя всяких классификаций, а в
    структурном -- школу Платона, сформулировавшего понятие идеи,
    которая отражается в бесконечном количестве вариантов, в
    конкретных вещах.
    #+END_QUOTE

    #+BEGIN_QUOTE
    Примерами аналитической типологии являются система Карла Юнга и
    Ганса Айзенка.
    #+END_QUOTE

*** Психосоматические типы; система Кречмера-Шелдона

    Психосоматические типы (первое название по Кречмеру, второе по
    Шелдону):

    - Атлет -- мезоморф -- мускулистый с широкими плечами и узкими
      бедрами. Склонны к взрывным реакциям (эпилептоиды).

    - Пикник -- эндоморф -- широкий с большим количеством жировой
      ткани. Стабильны и дружелюбны (циклотимики).

    - Астеник -- эктоморф -- длинный и тонкий. Холодны и углублены
      в себя (шизоиды). 

      Несмотря на некорректную экстраполяцию Кречмер вошел в историю
      благодаря идее единства психического и соматического.

*** Определение психологического типа

    Набор врожденных потребностей и стиль их удовлетворения определяют
    психологический тип человека.

    Психологический тип проявляется в стрессорной ситуации.

    Метод определения психологического типа с помощью опросников
    чреват ошибками вследствие сознательной или бессознательной лжи.

** Генетическая детерминированность психологического типа

   Мнение о роли врожденных факторов в психике и поведении человека --
   это вопрос мировоззрения. Несмотря на это, очевидно, что все
   признаки живого организма находятся под совместным влиянием и генов
   и среды.

*** Генетические и средовые влияния

    Тип стрессорной реакции почти полностью зависит от генотипа.

** Психологические типы А и Б

   Деление на поведенческие типы А и Б -- это аналитическая система.

   Два основных типа поведения при стрессе: "реакция бегства --
   борьбы" и "реакция затаивания". Тип поведения при стрессе определен
   генетически.

*** Поведения типа А -- "бегство -- борьба", поведение типа Б -- "затаивание"

    При социальном стрессе человек реагирует так же, как животные:
    либо поведение А, либо Б.

*** Тип стрессорной реакции -- А или Б -- генетически детерминирован

    Внешними воздействиями можно изменить величину, то не тип 
    стрессорной реакции.

    Тип стрессорной реакции -- это признак с высокой наследуемостью.

*** Поведения типа А и Б у человека

    Разделение людей по поведенческим типам А и Б было предложено
    кардиологами М. Фридменом и Р. Розенманом в 1959 году. Они первые
    обратили внимание на то, что для людей типа А в несколько раз выше
    риск ишемической болезни сердца, а это основная причина смерти в
    развитых странах.

    Поведенческий тип А характеризуется тремя А: агрессивностью,
    амбициозностью, активностью в общественной жизни. Для
    поведенческого типа А основу стрессорной реакции составляет
    секреция адреналина.

    Поведенческий тип Б характеризуется противоположными качествами:
    низкой агрессивностью, низкой амбициозностью, низкой активностью в
    общественной жизни. Для поведенческого типа Б основу стрессорной
    реакции составляет секреция кортизола.

    Деление на поведенческие типы А и Б -- это аналитическая
    система. Большинство людей относятся к промежуточному типу.

    #+BEGIN_QUOTE
    Ситуация с определением типа поведения человека примерно та же,
    что возникла бы при необходимости разделить всех людей на
    "высоких" и "низких".
    #+END_QUOTE

*** Эндокринный стресорный ответ типа А и Б

    Психологический тип определяется при стрессе. Стресс -- это
    системная реакция. Поэтому особенности поведения должны отражаться
    в эндокринных реакциях. Соответственно по эндокринным реакциям
    организма должно быть возможным предсказать тип поведения
    животного или человека при стрессе.

    У людей типа А преобладает активность мозгового слоя
    надпочечников, а у людей типа Б -- коркового. Соответственно,
    основным стрессорным гормоном для людей типа А является адреналин,
    а для людей типа Б -- кортизол.

    #+BEGIN_QUOTE
    Гены некоторых признаков наследуются совместно. Примеры такого
    сцепленного наследования многочисленны и порой неожиданны. У
    человека склонность к шизофрении сочетается с определенными
    папилярными узорами.
    #+END_QUOTE

*** Адаптивность психологических типов А и Б

    В зависимости от конкретных условий, вызвавших стресс,
    преимущество получают либо животные с поведением типа А, либо
    животные с поведением типа Б. Поэтому в эволюционном плане
    оптимальны те популяции, в которых существуют особи обоих типов.

    Поведение типа Б оказывается оптимальной стратегией, если задачей
    является не выполнение какой-либо задачи, а выживание. Еще один
    пример удачного применения стратегии Б является захват чужой
    территории. Вторжение всегда встретит отпор хозяина. Тихое
    "втирание" имеет больше шансов на успех.

*** Поведение типа А и Б в неконтролируемой ситуации

    Поведение типа Б является оптимальным в неконтролируемой
    стрессорной ситуации. У таких животных в результате
    неконтролируемого стресса повышается тревога, но не формируется
    выученная беспомощность.

    Только животные типа А после неконтролируемого воздействия
    начинают употреблять алкоголь.

*** Эндокринные реакции после неконтролируемого стресса у представителей типа А и Б

    После неконтролируемого стресса у животных поведенческого типа А
    нарушается торможение гипофиз-адреналовой системы по механизму
    отрицательной обратной связи. У животных поведенческого типа Б
    после неконтролируемого сресса увеличивается секреция кортизола,
    но торможение гипофиз-адреналовой системы по механизму
    отрицательной обратной связи не страдает.

    Ослабление регуляции гипофиз-адреналовой системы означает, что
    нарушена способность к торможению стрессорной реакции. Обратная
    связь -- это единственный механизм торможения эндокринного
    компонента стресса. При ослабленной чувствительности к сигналам
    обратной связи незначительные воздействия будут поддерживать
    постоянное состояние стресса организма.

*** Субъективизм понятия контролируемости

    При неконтролируемом стрессорном воздействии человек с поведенческим
    типом А может воспринимать ситуацию как контролируемую, если упорно
    будет реализовывать свою стратегию борьбы, несмотря на отсутствие
    реального результата.

    Поведение животных типа А лишено пластичности -- они реализуют
    присущий им тип поведения, несмотря на изменяющиеся или, напротив
    неменяющиеся обстоятельства. 

    Эта черта поведения типа А оказывается спасительной, когда субъект
    оказывается в очень тяжелой ситуации. Большая часть популяции,
    которая состоит из носителей поведенческого типа Б, после
    нескольких неудовлетворительных попыток начинают воспринимать
    ситуацию как неконтролируемую. В тоже время представители
    психологического типа А действуют, не поднимая головы, на
    бесконечно далекий горизонт. Такая стратегия поведения часто
    приводит к гибели особей такого психологического типа, но у них не
    вырабатывается выученная беспомощность.

    Субъективное восприятие ситуации как контролируемой позволяет
    избежать выученной беспомощности и депрессии даже при действии
    объективно неконтролируемого стрессорного воздействия.

    Для особей психологического типа Б пагубной оказывается ситуация в
    которой они вынуждены изменить окружающую их среду -- физическую
    или социальную, вместо того чтобы приспособиться к произошедшим
    изменениям, используя свою стратегию поведения -- затаивание.

    Следует подчеркнуть, что субъективизм в восприятии ситуации не
    является прерогативой человеческой психики. Если, скажем, крысам
    поведенческого типа А дать возможность реализовать свою
    поведенческую стратегию во время неконтролируемого болевого
    воздействия, то у них не разовьется выученная беспомощность и не
    будут ослаблены торсозные связи в гипофиз-адреналовой
    системе. Такую возможность можно предоставить животным, если
    подвергать их ударам электрическим током в большой клетке или не в
    одиночку. В большой клетке крысы будут бегать, в стае -- они будут
    драться друг с другом. То и другое поведение является проявляением
    их врожденной стратегии поведения. Таким образом, для человека
    поведенческого типа А простая мышечная нагрузка становится
    эффективным средством от развития депрессии.

    Реализация стратегии поведения, которая не обеспечена врожденными
    физиологичечкими механизмами, приводит к неблагоприятным для
    организма последствиям.

    При проведении турнира среди мышей типа Б у постоянных победителей
    подъем кортикостерона сохранялся дольше, чем у побежденных, что
    говорит о том, что они испытывали больший стресс, чем побежденные.

    Большинство людей имеет врожденную склонность к реакции
    затаивания, т.е. принадлежат к поведенческому типу Б.

    Поведенческий тип Б генетически передается по доминантному
    признаку (в потомстве родителей А и Б будут преобладать особи типа
    Б). По доминантному типу, как правило, наследуются признаки,
    которые увеличивают адаптивные возможности организмов.

    #+BEGIN_QUOTE
    Джек Лондон, постоянно описывая не просто носителей типа А, а
    успешных представителей этого типа, сам не смог реализовать
    присущую этому типу стратегию поведения. При походе на Клондайк он
    обморозился на первом перевале и попал в больницу. В поездке по
    островам Южных морей его свалила тяжелая тропическая
    лихорадка. Накопление опыта поражений во всех этих ситуациях, к
    тому же измена жены (см. "Маленькая хозяйка большого дома") -- все
    это привело к тому, что, несмотря на огромную популярност у
    читателей и финансовый успех, Джен Лондон покончил с собой в
    возрасте 40 лет.
    #+END_QUOTE

** Другие психологические типы

* Социальное поведение 

** Иерархия

   Доминанты -- особи, занимающие высшие позиции в иерархии.

   Субдоминанты -- особи, занимающие в иерархии положение после доминант.

   Субординанты -- особи, занимающие низшие места в иерархии.

   Доминирование в широком смысле -- это защита от социального давления
   со стороны других членов сообщества.

   Обладатели высшего социального ранга защищены от социального
   давления от других членов сообщества.

   Существование двух иерархий -- мужских и женских особей -- является
   общебиологической закономерностью.

*** Четыре шкалы социального ранга

    * доминирование в узком смысле -- ограничение доступа к витальным
      ресурсам
    * лидерство -- свобода перемещения в социальной структуре общества
      -- насколько человек ориентирован на поведение других людей
    * агрессивность -- частота побед при конфликтах
    * ранк самооценки -- определение человеком своей способности
      достичь какой-то цели

      Для общественных животных, в общем случае, социальная иерархия не
      является пирамидой.

    #+BEGIN_QUOTE
    Игра -- один из способов повышения самооценки.
    #+END_QUOTE

*** Соотношение социального ранга и психологического типа

    Представители типа Б занимают позиции субдоминантов в иерархии
    сообщества, а представители типа А -- и доминантов, и
    субординантов.

    Репродуктивнй успех субординантов гораздо ниже, чем у доминантов и
    субдоминантов. Репродуктивный успех доминантов и субдоминантов
    приблизительно одинаков.

*** Гормоны и социальный ранг

    Гормональные реакции отражают социальный ранг особи. Прямое
    влияние гормонов на социальный ранг животного отсутствует.

** Агрессивное поведение

*** Агрессивное поведение и гормоны

    Многие гормоны (кортиколиберин, вазопрессин, тестостерон) могут
    усиливать или ослаблять агрессивное поведени, но ни один из
    гормонов не индуцирует его. Гормона агрессии не существует.

    Андрогены определяют уровень агрессивности только тогда, когда их
    концентрация в крови выходит за границы физиологической
    нормы. Основным фактором, определяющим агрессивность, является
    человеческий опыт.

    Агрессивность в отличии от поведения типа А и Б, не служит основой
    для поведенческого типа, т.к. не закреплена генетически.

*** Асоциальное поведение и гормоны

    Не обнаружено соотвествия между высокой частотой асоциальных
    поведенческих актов и высокой концентрацией тестостерона или любых
    других гормонов.

*** Биологический смысл агрессии

    Основные функции агрессии: поддержание стабильности общества,
    обеспечение ресурсами, половой отбор, защита потомства, расселение
    популяции, обеспечение индивидуального пространства, социальная
    самоидентификация.

** Аффилиативное поведение 

   Аффиляция к своим основана на враждебности к чужим.

   Наличие или отсутствие аффилиативного поведения прямо связано с
   двумя стратегиями поведения: r-стратегией и K-стратегией, которые
   являются частными случаями r-стратегии и K-стратегии социальных
   контактов.

   При r-стратегии общение с незнакомой особью предпочтительнее.
   r-стратегия размножения: большое количество потомков, лишенных
   родительской опеки.

   При K-стратегии социальные контакты устанавливаются надолго и
   знакомая особь предпочтительнее. K-стратегия размножения:
   тщательный уход за небольшим количеством потомков.

*** Роль гормонов в родительском поведении

    Окситоцин и вазопрессин -- основные гомоны, обеспечивающие и
    стимулирующие родительское поведение. Окситоцин усиливает
    аффиляцию к "своим". Вазопрессин усиливает враждебность к "чужим".

*** Две стратегии социальных контактов у человека

    В эволюции человека r-стратегия вытесняется K-стратегией.

    Холодность или неприязнь женщины к своим детям -- варианты
    нормы. Это крайнее проявление r-стратегии размножения.

    Такие люди (особенно женщины) часто болезненно переживают свое
    равнодушие. Это состояние выделяют в особый невроз "плохой
    матери".

    Концентрация кортизола в крови растет во время беременности у всех
    женщин. Но ее увеличение больше у тех женщин, которые впоследствие
    проявляли более выраженное материнское поведение.

*** Аффилиация и социальное обучение

    Подражание, имитация -- основная форма обучения, в том числе, и у
    человека.

    С помощью условного рефлекса закрепляются навыки, приобретенные в
    процессе подражания.

    На основе потребности в социальной самоидентификации происходит
    формирование личности человека за счет подражания другим членам
    общества. Имитация поведенческих и психических реакций чаще всего
    происходит бессознательно.

*** Гносеологическое значение имитации

    Подражательное, имитационное обучение имеет важный аспект --
    обучение путем аналогии, т.е. самоподражательное обучение.

    Путем многократных имитаций различных конкретных ситуаций человек
    учится видеть в частном общее.

    #+BEGIN_QUOTE
    Нобелевская речь Конрада Лоренца так и называется "Аналогия как
    источник знаний".
    #+END_QUOTE

*** Склонность к имитации и пластичность поведения представителей поведенческого типа Б

    Представители поведенческого типа Б склонны имитировать поведения
    других представителей своего сообщества.

** Копулятивное поведение

   Поведение спаривания у человека не запускается гуморальными
   факторами, как у животных. Копулятивное поведение индуцируется
   сенсорыми стимулами. Гормональные и феромональные сигналы лишь
   обеспечивают и модулируют поведение совокупления.

*** Роль тестостерона

    Андрогены оказывают организующее и обеспечивающее влияние на
    копулятивное поведение человека.

    Не обнаружено зависимости между уровнем потенции мужчин и либидо
    женщин и концентрацией отдельных гормонов, если она не выходит за
    пределы физиологической нормы.

    После кастрации может сохраняться эрекция и, соответственно,
    способность к половому акту за счет секреции андрогенов
    надпочечниками.

    Концентрация тестостерона в крови отражает силу мотивации
    поведения совокупления.

    Копулятивное поведение обеспечивается не только тестероном, но и
    его соотношением с рядом других гормонов.

    Во многих тканях биологическую активность проявляет не сам
    тестостерон, а его метаболиты: эстрадиол и дигидротестостерон
    (ДГТ).

    Помимо тканевого метаболизма тестостерона, для нормального
    мужского поведения необходимо взаимодействие тестостерона с
    дигидротестостероном, образующимся в предстательной железе и в
    крайней плоти, а также с гипофизарным гомоном пролактином. Причем
    нурушения эрекции и эякуляции связаны главным образом с изменением
    уровня дигидротестостерона, а нарушение либидо -- с тестостероном.

*** Роль других гуморальных факторов

    Гонадолиберин стимулирует копулятивное поведение человека.

    При повреждении отделов гипоталамуса, содержащих нейроны,
    синтезирующие гонадолиберин, падает либидо и исчезает способность
    к совокуплению. Функции восстанавливаются при компенсаторном
    введении синтетического гонадолиберина.

    При стрессе тормозится репродуктивная функция. Это происходит за
    счет прямого торможения кортиколиберином синтеза гонадолиберина.

    При первичном приеме опиаты резко повышают потенцию (так
    называемый "медовый месяц героина"). Но при регулярном применении
    они снижают потенцию, а затем способность к половому акту исчезает
    полностью.

    В малых дозах алкоголь является афродизиаком, в больших --
    тормозит половую мотивацию, хроническое употребление тормозит
    репликативную функцию и приводит к инволюции вторичных половых
    признаков.

** Феромоны

*** Общие представления о феромонах

    Феромоны -- биологические активные вещества, которые синтезируются
    в специальных орагнах, выделяются во внешнюю среду и изменяют
    поведение представителей других видов.

    Феромоны изменяют поведение человека, оставаясь неосознанными.

    Феромоны только модулируют, но не индуцируют поведение других людей.

*** Физиология феромонов

    Феромоны содержатся во всех жидкостях, которые выделяются организмом
    в окружающую среду.

    Сам по себе экскрет кожных желез по большей части не имеет
    запаха. В пахучие соединения он превращается в результате
    жизнедеятельности разнообразных бактерий.

    Аксиллярный орган -- (axilla -- подмышка) -- подмышки. Состоит из
    апокринных желез, сальных желез, потовых желез, постоянно
    присутствующей на коже человека микрофлоры и волосяного
    покрова. Основной регулятор аксиллярного органа -- продукция
    половых гомонов в организме. Место наиболее активного выделения
    феромонов.

    Состав феромонов определяется:

    - половыми гормонами
    - индивидуальными генетическими особенностями
    - функциональным состоянием организма

    #+BEGIN_QUOTE
    Вещества, попадающие на слизистую оболочку носовых проходов, через
    подслизистые пространства быстро проникают в спинно-мозговую
    жидкость и мозговой кровоток.  
    #+END_QUOTE

*** Репродуктивное поведение и феромоны

    Запах женщины превлекает мужчин благодаря феромонам и копулинам.

    Основные компоненты мужских феромонов являются метаболитами
    тестостерона. Два наиболее изучаемых мужских феромона -- это
    андронстенол и андронстенон.

    Запах мужского пота содержит как привлекательный для женщин
    компоненты, так и компоненты, которые женщина оценивает
    отрицательно. Общая оценка зависит от концентрации отдельных
    компонентов.

    Феромоны мужчин изменяют поведение женщин даже в таких низких
    концентрациях, которые не вызывают ощущение запаха.

*** Родительское поведение и феромоны

    Феромоны способствуют установлению взаимной привязанности между
    матерью и ребенком.

    Феромоны отца необходимы для нормального развития детенышей
    крыс. У человека, по всей вероятности, феромоны способствуют
    установлению привязанности между ребенком и отцом.

*** Социальная самоидентификация и феромоны

    Набор феромонов человека определяется его генотипом. Чем больше
    различий в генотипе, тем более "чужим" кажется запах. Набор
    феромонов представителя другой рассы, кажется человеку особенно
    резким.

*** Феромоны и общение с животными

    Кайромоны -- феромоны, изменяющие поведение представителей других
    видов.

    Общим правило почти всех животных является менее жесткая агрессия
    по отношения к женским особям. Отношение животных к женщинам
    значительно мягче, чем к мужчинам.

    У ребенка, не достигшего половой зрелости, продукция половых
    гормонов очень мала. Соответственно отсутствуют и половые
    феромоны. Отношение же к детенышам у большинства видов животных
    весьма терпимое. Поэтому, столкнувшись с ребенком, дикий зверь
    может и не тронуть его.

*** Роль феромонов в современном социальном поведении человека

** Алкоголь

   Чувствительность и устойчивость к алкоголю определяется на 90%
   средовыми влияниями.

   Эффекты:

   - усиливает пищевое поведение, блокируя глюконеогенез
   - усиливает эйфорию, либо гипоманиакальное состояние (но не
     индуцирует их)
   - стресс-протективное действие (тормозит развитие выученной
     беспомощности после неконтролируемого стресса)
   - увеличивает либидо
   - уменьшает либидо (в больших дозах)
   - дезориентирует поведение в больших дозах
   - индуцирует деградацию личности (при хроническом применении)

* Половые различия

  Различия между полами имеют статистический характер. 

  Легко указать на женщину, которая выше большинства мужчин, но
  существование высоких женщин не опровергает общую закономерность о
  большей длине тела мужчин по сравнению с женщинами.

** Понятие пола

   Пол -- совокупность взаимно контрастирующих генеративных и связанных с
   ними признаков одного вида.

*** Хромосомный этап формирования пола

    Пол живого организма определяется во время оплодотворения. В ядрах
    клеток человека одна пара хромосом различна у мужчин и женщин. У
    женщины эта пара похожа под микроскопом на две буквы X, а у мужчин
    -- на буквы XY. Соответственно эти хромосомы называются "икс" и
    "игрек". Женский генотип XX обусловливает то, что все яйцеклетки
    содержат X-хромосому, а мужской XY -- то, что в одной половине
    сперматозоидов находится X-хромосома, а в другой Y-хромосома. В
    зависимости от того, какой сперматозоид проникнет в клетку первым,
    такой генотип и будет у эмбриона. Если X, то разовьется женский
    организм, а если Y -- мужской.

    Если в результате каких-то нарушений оплодотворенная яйцеклетка
    будет иметь только одну хромосому, то судьба эмбриона будет
    зависеть от того, какая это хромосома. Генотип Y0 нежизнеспособен,
    а при генотипе X0 разовьется и родится женская особь, но со слабо
    развитыми наружными и внутренними половыми органами и мужским
    типом телосложения. Таким образом, женский пол первичен по
    отношению к мужскому.

*** Гонадный этап формирования пола

    В эмбрионах с генотипом XY зачаточные гонады превращаюются в
    семенники, которые начинают синтезировать андрогены.

    Гормоны оказывают влияние на формирование половых особенностей
    психики и поведения исключительно на ранних этапах индивидуального
    развития. Влияние половых гормонов на специфичный вид психики
    являются организующим.

*** Соматический этап формирования пола

    Под влиянием андрогенов формируются особенности строение тела
    мужской особи.

    Если под влиянием каких-либо внешних факторов (стресс матери,
    прием ею фармакологичеких препаратов и т.д.) содержание андрогенов
    в крови плода уменьшено, то формирование гениталий идет по
    женскому типу, несмотря на мужской генотип. Особенно опасны
    лекарственные средства на основе стероидных гормонов.

*** Нейронный этап формирования пола

    Под влиянием андрогенов и эстрогенов формируются особенности
    строения головного мозга мужчин и женщин.

    Нейронный пол является не альтернативным признаком, а
    количественным.

    Основные различия между женской и мужской ЦНС:
    
    - большая скорость метаболизма глюкозы в мозге у женских особей
    - больший мозговой кровоток у женских особей
    - больше количество синапсов у женских особей
    - большая ассиметрия мозга у мужских особей (не только по весу)
    - большее количество межполушарных связей у женских особей (не
      только мозолистое тело)
    - количество серого вещества и плотность нейронов в области
      речевых центров в коре больше у женщин
    - ядро ложа конечной полоски (BNST) больше у мужских особей
      (именно с ним связывают устойчивость организма к стрессу)
    - сенсорные и моторные системы у женских особей действуют лучше
      
*** Социальный этап формирования пола

*** Возможные последствия рассогласования этапов

    Каждый из этапов половой диффиренцировки не жестко детерминирован
    предыдущим. Это приводит к тому, что строго говоря, пол не
    является альтернативным признаком.

    Синдром Морриса. Возможна ошибка на соматическом этапе
    формирования пола. При генотипе XY из-за отсутствия рецепторов
    андрогенов в некоторых клетках зародыша и, соответственно,
    нечувствительности этих участков к андрогенам рождается ребенок с
    так называемой тестикулярной феменизацией, которая также
    называется синдромом Морриса. Мутация, вызывающая этот синдром
    встречается довольно часто -- 1:65000. Внешне это высокая,
    стройная, статная, физически сильная женщина без матки, с малым
    влагалищем, семенниками, конечно, не менструирующая и нерожающая,
    но в остальном способная к сексуальной жизни и сохраняющая
    нормальное влечение к мужчинам.

    До сравнительно недавнего прошлого мутантов Морриса было довольно
    много среди выдающихся спортсменок. С 1966 года все спортсменки
    проходят специальный контроль на генетическую пренадлежность к
    женскому полу.

    Достаточно распространено нарушение формироваие наружных половых
    органов. В результате они имеют смешанный (диспластический) тип
    сроения. Это происходит из-за того, что и мужские и женские
    гениталии развиваются из одного участка зародыша (т.е. они
    гомологичны друг другу). Если у такого ребенка при рождении пол
    определялся на глаз, то после появление вторичных половых
    признаков паспортный пол приходится менять.

** Фундаментальные различия двух полов

   Существуют фундаментальные различия между мужским и женским полом,
   которые проявляются не только в функции воспроизводства, но и в
   приспособительных возможностях организма. Эти отличия генетически
   детерминированы, и их невозможно нивелировать внешними воздействиями.

*** Биологическая целесообразность существования двух полов
    
    Можно изъять из популяции 90% или даже больше самцов, и это не
    скажется на темпах воспроизводства популяции. Тем не менее из
    примерно четерех с половиной тысяч видов млекопитающих только
    гиены пошли по такому пути. В большинстве случаев самцы составляют
    приблизительно половину от общего количества особей.

    Генетическое разнообразие самцов значительно больше чем у
    самок. Это позволяет приспосабливаться к изменяющейся среде
    обитания. Большая часть генетических изменений в новом поколении
    самцов оказывается неудачной и гибнет, не оставив
    потомства. Мужской пол представляет собой "испытательный полигон"
    эволюции.

    Самки генетически более стабильны, потому что только от них
    зависит воспроизводство популяции.

*** Генетическая стабильности и индивидуальная пластичность женских особей

    Женские особи генетически стабильнее мужских. В то же время они
    легче поддаются воздействиям среды, то есть обладают высокой
    средовой изменчивостью.

    Преимущества женского строения ЦНС проявляются только при низком
    уровне стресса.

    Среди женщин более распространены психические болезни, в
    возникновении которых велика роль стрессорных факторов.

*** Мужские особи устойчивы к стрессу

    Самцы обладают высокой генетической и низкой средовой
    изменчивостью. 

    Мужские особи устойчевее к стрессу, чем женские.

    Среди мужчин более распространены психические болезни имеющие
    явный наследственный механизм (например различные формы
    слабоумия).

    #+BEGIN_QUOTE
    Несмотря на идеологическое значение полета Валентины Терешковой,
    полеты женщин в космос были прекращены на десятилетия. 
    #+END_QUOTE

*** Накопление ресурсов и циклирование женских особей

    Физиология и поведение женских особей, в отличие от мужских,
    циклично меняется.

    Изменения когнитивных способностей в менструальном цикле
    незначительны, но в менструальном цикле значительно колеблется
    аффектиное состояние.

    Два пола различаются затратами на воспроизводство одного
    потомка. Затраты женской особи на несколько порядков выше, чем
    затраты мужской особи. Поэтому женские особи более, чем мужские,
    склонны накапливать ресурсы. На физиологическом уровне -- это
    накопление жира. На поведенческом -- это накопление витальных
    ресурсов.

    Мужским особям в большей степени, чем женским, свойственна
    потребность в лидерстве.

    Женские особи менее агрессивны во внутривидовых контактах.

*** Мужской и женский психологические типы

    Мужская и женская психика и поведение, как и другие
    психологические типы, различаются набором потребностей и стилем
    стрессорной реакции. Основное различие потребностей: у мужчин
    потребность в лидерстве, у женских -- в накоплении витальных
    ресурсов. Мужские особи более устойчивы к стрессу, чем женские.

    Различие между типами "мужчина" и "женщина" близко к различиям
    между типами А и Б, соответственно, и r- и K-стратегиями
    социальных контактов, соответственно.

** Когнитивные различия

   Среднее значение коэффицента интеллектуальности мужчин и женщин
   одинаково.

   Разлчие в отдельных способностях взрослых мужчин и женщин
   обусловлены не разным гормональным фоном, а теми особенностями
   физиологии и строения нервной системы, которые сформировались в
   эмбриональный период под влиянием половых гомонов.

   Мужчины лучше выполняют пространственные тесты. 

   Женщины лучше классифицируют предметы по формальным признакам.

   У женщин выше вербальная активность.

   Мужской интелект региден, женский интеллект интуитивен.

** Гендерные различия

   Гендер -- стереотипные представления о формах поведения и
   психологических особенностях личности мужчины и женщины. Многие из
   них обусловлены конкретной культурой, но большая их часть
   обусловлено биологическими закономерностями -- драматической
   разницей энергетического вклада двух полов в производство потомства.

*** Две системы этики

    Двойной этической стандарт -- для мужчин и для женщин --
    обусловлен разной репродуктивной ролью двух полов.

    Мужские особи стараются максимально распространить свои гены. В
    тоже время, поскольку производство потомка очень затратно, женские
    особи не могут спариваться с первым попавшимся партнером.

*** Социальный смысл существования двух полов

    Принадлежность к определенному полу служит удовлетворению
    потребности в социальной самоидентификации.

** Гомосексуализм    

   Гомосексуализм -- сексуальная ориентация на людей своего
   пола. Бывает облигатным (когда эротические контакты с
   противоположным полом исключены) и факультативным (бисексуализм).

   В основе факультативного гомосексуализма лежат в первую очередь не
   биологические, а психологические и социальные механизмы.

   Биологическую основу можно обнаружить в части случаев облигатного
   гомосексуализма. Решающим для формирования сексуальной ориентации
   может быть влияние гомонов в процессе эмбрионального
   развития. Например, чем больше стресса испытала беременная, тем
   выше вероятность гомосексуальности потомка. Это связано с
   антагонизмом глюкокортикоидов и андрогенов.

* Ритмы жизнедеятельности

** Биологические ритмы

   Биологический ритм -- это колебательный процесс в живой системе,
   состоящий из волнообразного чередования фаз напряжения и
   расслабления.

   Организация единого ритма организма невозможна при участии одной
   нервной системы. Только гуморальный сигнал, который распространяется
   по всему органиму и действует длительно, может обеспечить интеграция
   многочисленных колебательных процессов в единый ритм.

*** Основные принципы биоритмологии

    По величине периода колебаний:

    - ультрадианные -- несколько часов (например ритм двигательной
      активности кишечника)
    - циркодианные -- околосуточные -- 20-28 часов (большинство
      психических и физиологических процессов)
    - инфрадианные -- несколько суток
    - циркасептальные -- околонедельные
    - цирканульные -- окологодовые
    - мегаритмы -- несколько лет (например 11-летний цикл,
      обнаруживаемый во многих биологических системах, обусловленный
      колебанием солнечной активности)

      Большинство ритмов зависят от изменения освещенности.

      Опыты по изоляции людей показали, что при отсутствии внешних
      факторов (солнца, часов), субъективный суточный ритм начинает
      постепенно удлиняться.

*** Суточные и сезонные ритмы

    Биологический смысл суточных ритмов заключается в том, чтобы
    активность проявлялась в определенное время суток, наиболее
    благоприятное для данного организма.

    Максимальная активность многих эндокринных систем приурочена к
    утреннему пробуждению.

    Учет циркадных ритмов важен при приеме лекарственных средств,
    особенно, если это связано с эндокринной системой.

    Для зимы характерна повешенная секреция гормонов щитовидной железы
    и адреналина, что увеличивает теплопродукцию.

*** Мелатонин и суточные ритмы

    Эпифиз, получая сигналы непосредственно от сетчатки глаза,
    уменьшает синтез и секрецию мелатонина -- основного гуморального
    регулятора суточной и годичной ритмики.

    Центральную роль в организации всех ритмов играет
    супрахиазматическое ядро гипоталамуса. Оно воспринимает сигналы от
    сетчатки глаза и имеет собственный водитель ритма.

    Все перефирические, внутренние органы имеют и свои собственные
    пейсмейкеры.

    Эпифиз связан с гипоталамусом системой сложных связей.

    #+BEGIN_QUOTE
    Хорошо известно, что органы -- сердце, кишечник и т.д. --
    выделенные из организма и помещенные в физиологический раствор,
    обагощенный кислородом, какое-то время живут, т.е. демонстрируют
    функциональную активность. Причем эта активность ритмически
    ораганизована, что обусловлено наличием в этих органах собственных
    водителей ритма.
    #+END_QUOTE

** Сон

   Сон -- активный процесс.

   Во время сна не проиходит уменьшения средней частоты активности
   нейронов по сравнению с состоянием спокойного бодрствования. На
   отдельных стадиях сна активность может быть даже выше, чем при
   бодрствовании в состоянии напряжения.

   Для объективного изучения сна используется полисомнография.

*** Структура сна

    Сон состоит из нескольких циклов, каждый из которых длится
    приблизительно полтора часа. Каждый цикл включает в себя две
    стадии -- медленный и быстрый сон.

    Медленный сон:

    1) Стадия дремоты.

       Исчезает альфа-ритм ЭЭГ. 

       Стадия занимает 5-10% от длины цикла.

    2) Появление "сонных веретен" (регулярные колебания с частотой
       14-18 Гц)

       Появление первых же веретен свидетельствует об отключении
       сознания. На этой стадии, в паузах между веретенами человек
       легко просыпается при внешней стимуляции. 

       Стадия занимает 40-50% от длины цикла.

    3) Первая стадия дельта-сна. 

       Дельта-волны занимают 30-40% от времени стадии.

    4) Вторая стадия дельта-сна. Дельта-волны занимают больше 50%
       времени стадии -- это стадия наиболее глубокого сна. При этом
       максимально снижается мышечный тонус, дыхание и сердцебиение
       становятся редкими и регулярными, понижается температура тела и
       отсутствуют движения глаз. Присходит наиболее полное отключение
       от мира, для пробуждения требуется максимальная стимуляция. При
       пробуждении человек с трудом ориентируется в пространстве и
       времени (неправильно оцинивает сколько он спал).

       Первая и вторая стадия дельта-сна занимают 20-25% от длины цикла.

       Быстрый или парадоксальный сон (15-25% от длины цикла):

    - глубокое расслабление скелетных мышц (низкая амплитуда
      электромиограммы)
    - быстрые низкоамплитудные ритмы ЭЭГ, очень похожие на ЭЭГ
      бодрствующего человека
    - "вегетативная буря" -- усиление влияния хаотической активности
      симпатической и парасимпатической нервной системы на висцеральные
      функции (аритмичное сердцебиение, колебания артериального
      давления, прерывистое дыхание, эрекция полового члена у мужчин и
      клитора у женщин, усиление мозгового кровотока)
    - на стадии быстрого сна происходит большая часть запомнившихся
      сновидений
    - быстрые движения глаз (БДГ они же REM)

      Сон обычно состоит из 4-5 циклов. В двух первых преобладает
      дельта-сон, а доля быстрого сна не велика. В последующих циклах
      увеличивается доля быстрого сна, а дельта сон резко сокращается или
      вообще отсутствует.

*** Гуморальные факторы и сон

    Во время быстрого сна снижается секреция почти всех гормонов. В
    стадии быстрого сна некоторые эндокринные системы активируются.

    Гуморальные механизмы не являются определяющими для запуска и
    поддержания сна (сиамские близнецы могут спать поотдельности).

*** Сон и депрессия
    
    Во время депрессивного сна парадоксальный сон наступает быстрее,
    чем в здоровом состоянии, и занимает больше времени. Это
    применяется при диагностике.

    Изменение доли, интенсивности и времени возникновения быстрого сна
    отмечается не только у больных психотическими формами депрессии,
    но и у здоровых людей с дисфорическими расстройствами.

    При длительном сне изменяется его структура -- быстрый сон
    занимает половину времени от всей продолжительности сна. 

    Для субдепрессии характерно увеличение длительности сна.

    Одним из симптомов депрессии является инверсия околосуточного
    ритма настроения. Хорошее настроение после пробуждения постепенно
    ухудшается к вечеру.

    Лишение (быстрого) сна -- эффективный метод лечения депрессии. При
    этом надо понимать, что если для больных депрессией лишение сна
    облегчает болезненное состояние, то здоровым людям это наносит вред.
