* JavaScript

** Блочный текстовый редактор

** Существующие встраиваемые редакторы

*** Prose mirror

    http://prosemirror.net/

*** Substance

    http://substance.io/

** Если делать самому

*** Как поймать enter?
   Похоже самым простым способом будет множество тексовых полей, у
   которых на enter висит добавить новое поле после текущего.

   Как поймать enter:

   : <form name="chatline" ... >
   :   <input type="text" />
   :   <input type="submit" />
   : </form>
   :    
   : $("form").submit(function() {
   :   //there you go, you caught your enter
   : });

*** Как сгенерировать uuid?

   Для текстовых полей наверное надо будет генерить идешники. Как-то так:

   : var uuid = guid();

*** Как сделать это по-простому?

    Лоскутное одеяло из партиалов. Есть кнопки: добавить параграф,
    добавить цитату. При нажатии уходит ajax-запрос, который
    возвращает куски формы. Таким образом набивается форма. 

    Между блоками можно вставить тот же самый набор кнопок, только
    скрывающийся до полоски. Навел мышку на полоску -- увидел полный
    набор кнопок.

** Everything else

*** blast

    Blast.js separates text in order to facilitate typographic
    manipulation. It has four delimiters built in: character, word,
    sentence, and element. Alternatively, Blast can match custom
    regular expressions and phrases.

    http://julian.com/research/blast/

*** datatables

    http://datatables.net/

*** grid

    Нужно что-то для отрисовки дашборда.

    https://github.com/ubervu/grid

    https://github.com/ducksboard/gridster.js

*** countdown

    http://hilios.github.io/jQuery.countdown/examples/multiple-instances.html
